### ISSUE TITLE
Feature request: mpg restore from snapshot

### ISSUE THREAD

**Issue by webchi** [yandex-cloud/terraform-provider-yandex#103]
Is it hard to add possibility to create managed postrgres cluster from database snapshot? 
API is available https://cloud.yandex.ru/docs/managed-mysql/api-ref/Cluster/restore

**Comment by GennadySpb** [comment]
Hi @webchi !
Could you please explain in detail your use case for the requested feature?

**Comment by webchi** [comment]
@GennadySpb Hi. I have test environment and later I will have dynamic environment per feature brunch. And for this envs I need a copy of production database. Now I have to use restore snapshot feature into web interface, but wish to add some automation here.
Thanks

**Comment by apilikov** [comment]
Thanks for reaching out. As of now the issue is not on the team's schedule, but did you consider using some automation that CLI/API provides? Seems like using Terraform here is redundant as it does not imply managing long-lived resources. Thank you.

**Comment by webchi** [comment]
Yes, possibly so.

**Comment by superbotan** [comment]
Hello!
Thank you for your question. Now it is possible to create a cluster from a backup. Please use the `restore` block.
https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/mdb_postgresql_cluster#restore

**Comment by webchi** [comment]
> Hello!
> Thank you for your question. Now it is possible to create a cluster from a backup. Please use the `restore` block.
> https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/mdb_postgresql_cluster#restore

Great news! Thank you.
