### ISSUE TITLE
Unable to specify folder_id for MongoDB cluster

### ISSUE THREAD

**Issue by DariaVasilenko** [yandex-cloud/terraform-provider-yandex#104]
I tried to create a MongoDB cluster using yandex_mdb_mongodb_cluster resource. 

resource yandex_mdb_mongodb_cluster mongo {
  folder_id   = var.folder_id
  name        = var.name
  
  environment = var.mongo_environment
  network_id  = var.network_id
  labels      = var.labels
 ...
}

ER: terraform plan displays new MongoDB cluster to add

AR: I'm getting error

Error: "folder_id": this field cannot be set

  on ..\..\modules\yandexcloud\mongo\main.tf line 13, in resource "yandex_mdb_mongodb_cluster" "mongo":
  13: resource yandex_mdb_mongodb_cluster mongo {

When folder_id is not specified, terraform plan works as expected.

**Comment by asalimonov** [comment]
Thanks for the bug report. We will fix it in the next sprint.

**Comment by apilikov** [comment]
The issue has been resolved. Thank you!
