### ISSUE TITLE
Changing platform_id of instance forces recreation of resource

### ISSUE THREAD

**Issue by Nyoroon** [yandex-cloud/terraform-provider-yandex#11]
But it shouldn't.
```
platform_id:                        "standard-v1" => "standard-v2" (forces new resource)
```

**Comment by GennadySpb** [comment]
Hello! 

It's by design. Check this [doc](https://cloud.yandex.com/docs/compute/concepts/vm-platforms).

**Comment by Nyoroon** [comment]
But recreation of resource isn't required, you can just stop instance, change platform_id and start it (just like changing cores or memory).

**Comment by GennadySpb** [comment]
You right! 

Code arrived. Will be included in the next release.

**Comment by GennadySpb** [comment]
Version **0.5.2** released.
