### ISSUE TITLE
updating node group is not graceful

### ISSUE THREAD

**Issue by Goodluckhf** [yandex-cloud/terraform-provider-yandex#113]
I have `deploy_policy` 
`deploy_policy {
  max_unavailable = 0
  max_expansion   = 1
}`

And I tried to update 
`scale_policy {
  fixed_scale {
    size = 2
  }
}`
to 
`scale_policy {
  fixed_scale {
    size = 3
  }
}`

So this change seems to be not breaking. And anyway even if it has to update every node in node group I thought it should have processed like this:
1) create new node with new configuration
2) delete old one
3) ...
But actual behaviour was
![image](https://user-images.githubusercontent.com/9287861/94927039-66d3e600-04ca-11eb-896c-a416a4092481.png)

**Comment by seukyaso** [comment]
On latest terraform version, change in this parameter should not cause recreation of the node group.
Try to update the plugin to latest version.
If that doesn't help, please provide full plan section, so we can confirm, what change in your tf configs is causing this.

**Comment by Goodluckhf** [comment]
Ok we can don't take into account that case. Let's imagine that I made some change which can lead to recreation of `node group` like in my case. Why does it firstly destroy old `node group` and then create it. If it can process full recreation gracefully I would not make any sense recreating node group or just change one parameter

**Comment by candiduslynx** [comment]
> Ok we can don't take into account that case. Let's imagine that I made some change which can lead to recreation of `node group` like in my case. Why does it firstly destroy old `node group` and then create it. If it can process full recreation gracefully I would not make any sense recreating node group or just change one parameter

https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations
You can setup your resource with lifecycle configuration, this should help.

**Comment by baranov1ch** [comment]
> Ok we can don't take into account that case. Let's imagine that I made some change which can lead to recreation of `node group` like in my case. Why does it firstly destroy old `node group` and then create it. If it can process full recreation gracefully I would not make any sense recreating node group or just change one parameter

There are certain fields which cannot be changed without nodegroup re-creation. In most cases, there is no any good reason for it apart from it is not yet implemented on the server-side (for instance node labels, taints, allowed unsafe sysctls). Ultimately there will be no such fields. Plz, file a bug for a particular fields you want to be changed without re-creation, together with real-life scenarios which are broken, so we can prioritize work on them.
