### ISSUE TITLE
Внутренний балансировщик со статическим ip

### ISSUE THREAD

**Issue by Wolfeg** [yandex-cloud/terraform-provider-yandex#114]
В [документации](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/lb_network_load_balancer) описан процесс создания внутреннего балансировщика:
```
internal_address_spec
{
  subnet_id
  address
  ip_version
}
```
при указанные статического ip получаем ошибку `rpc error: code = NotFound desc = Address not found`

**Comment by Wolfeg** [comment]
тоже самое касаемо создания внутреннего loadbalancer из под managed k8s - возможно лишь без указания ip
использую аннотации:
```
yandex.cloud/load-balancer-type: "Internal"
yandex.cloud/subnet-id: "<subnet-id>"
```

**Comment by theigel** [comment]
https://cloud.yandex.ru/docs/load-balancer/concepts/internal-load-balancer

> Внутренний IP-адрес назначается балансировщику случайно из диапазона адресов подсети.

Внутренний балансировщик в настоящее время не поддерживает явное указание адреса.

**Comment by apilikov** [comment]
The issue has been resolved recently. Feel free to reopen if the problem is still there. Thank you!
https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/lb_network_load_balancer#address
