### ISSUE TITLE
Нет проверки при создании iam

### ISSUE THREAD

**Issue by Stayer** [yandex-cloud/terraform-provider-yandex#117]
В вашем же примере https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/iam_service_account есть такой код

```
resource "yandex_iam_service_account" "sa" {
  name        = "VM Manager"
  description = "service account to manage VMs"
}
```

Что является некорректным, так как при пользовании terraform выпадает ошибка:
`- name: Field does not match the pattern /[a-z]([-a-z0-9]{0,61}[a-z0-9])?/`

Добавьте проверку на этапе plan, в других ресурсах она у вас есть

**Comment by seukyaso** [comment]
Спасибо за замечание. В ближайшее время мы поправим документацию в этом месте.
