### ISSUE TITLE
Resource request: service account key, api key and access key resources

### ISSUE THREAD

**Issue by Nyoroon** [yandex-cloud/terraform-provider-yandex#12]
With encryption like
https://www.terraform.io/docs/providers/google/r/google_service_account_key.html
https://www.terraform.io/docs/providers/aws/r/iam_access_key.html

**Comment by GennadySpb** [comment]
Hi! Thanks for issue.

If you missed it, you can now use the SA access key https://www.terraform.io/docs/providers/yandex/r/iam_service_account_static_access_key.html

**Comment by GennadySpb** [comment]
@Nyoroon Hello!

I am pleased to announce that all types of keys as resources were supported has been released.

[0.13.0](https://github.com/terraform-providers/terraform-provider-yandex/blob/master/CHANGELOG.md#0130-september-23-2019)

**Comment by Nyoroon** [comment]
Thanks!
