### ISSUE TITLE
failed to get default storage client при apply 

### ISSUE THREAD

**Issue by Peter-Idea** [yandex-cloud/terraform-provider-yandex#121]
При попытке применить план терраформ выдает сообщение об ошибке:
_Error: error getting storage client: failed to get default storage client_

Файл конфигурации **yc.tf**:

terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
      **version = "0.46.0"**
    }
  }
}

 
provider "yandex" {
  service_account_key_file = "key.json"
  cloud_id  = "XXXX"
  folder_id = "XXXX"
  zone      = "ru-central1-a"
}

resource "yandex_storage_bucket" "test" {
  bucket = "test-test"
}

успешно проходят
terraform init
terraform plan

а 
_terraform apply_ 

выдает ошибку:

_yandex_storage_bucket.test: Creating...

Error: error getting storage client: failed to get default storage client

  on yc.tf line 20, in resource "yandex_storage_bucket" "test":
  20: resource "yandex_storage_bucket" "backups" {_

**Comment by GennadySpb** [comment]
Hi @Peter-Idea !

Your need to provider [static access key](https://cloud.yandex.com/docs/iam/concepts/authorization/access-key) (Access and Secret) to create storage client to work with Storage Service. To create them you need Service Account and proper permissons.

Full example
```
terraform {
  required_providers {
    yandex = {
      source  = "yandex-cloud/yandex"
      version = "0.47.0"
    }
  }
}

locals {
  folder_id = "XXXX"
}

provider "yandex" {
  folder_id = local.folder_id
  zone      = "ru-central1-a"
}

// Create SA
resource "yandex_iam_service_account" "sa" {
  folder_id = local.folder_id
  name      = "sa123"
}

// Grant permissions 
resource "yandex_resourcemanager_folder_iam_member" "sa-editor" {
  folder_id = local.folder_id
  role      = "storage.editor"
  member    = "serviceAccount:${yandex_iam_service_account.sa.id}"
}

// Create Static Access Keys
resource "yandex_iam_service_account_static_access_key" "sa-static-key" {
  service_account_id = yandex_iam_service_account.sa.id
  description        = "static access key for object storage"
}

// Use keys to create bucket
resource "yandex_storage_bucket" "test" {
  access_key = yandex_iam_service_account_static_access_key.sa-static-key.access_key
  secret_key = yandex_iam_service_account_static_access_key.sa-static-key.secret_key
  bucket     = "test-test-foobar"
}
```

**Comment by eugenberend** [comment]
Why not to add this to terraform provider documentation?
It is always very confusing when example from docs doesn't work.

**Comment by Peter-Idea** [comment]
Спасибо @GennadySpb, с такими поправками **заработало:**

terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
      version = "0.46.0"
    }
  }
}

provider "yandex" {
  service_account_key_file = "key2.json"
  cloud_id  = "XXXX"
  folder_id = "XXXX"
  zone      = "ru-central1-a"
}


resource "yandex_storage_bucket" "test" {
  **access_key ="XXXX"
  secret_key ="XXXX"**
  bucket   = "test"
}

Хорошая идея добавить эту информацию в доки.

**Comment by pashtet04** [comment]
Пытаюсь сделать `terraform import` для `bucket` и падает с такой же ошибкой

```
yandex_storage_bucket.kubernetes_pvc_rwx_bucket: Importing from ID "bucketname"...
yandex_storage_bucket.kubernetes_pvc_rwx_bucket: Import prepared!
  Prepared yandex_storage_bucket for import
yandex_storage_bucket.kubernetes_pvc_rwx_bucket: Refreshing state... [id=bucketname]
╷
│ Error: error getting storage client: failed to get default storage client
```

Несмотря на то что, я сервисный аккаунт импортнул ранее и описал в коде, а ключи импортить вроде нельзя.
Получается, что импортнуть бакет в состояние уже никак нельзя?

**Comment by ArtemKaba** [comment]
Hi
I have a same question:
if I remove the bucket from the terraform state like this
```
$ terraform state list
module.storage-test["infra-test-bucket"].data.aws_iam_policy_document.this[0]
module.storage-test["infra-test-bucket"].data.yandex_client_config.client
module.storage-test["infra-test-bucket"].random_string.unique_id
module.storage-test["infra-test-bucket"].yandex_iam_service_account.storage_admin[0]
module.storage-test["infra-test-bucket"].yandex_iam_service_account_static_access_key.storage_admin[0]
module.storage-test["infra-test-bucket"].yandex_resourcemanager_folder_iam_member.storage_admin[0]
module.storage-test["infra-test-bucket"].yandex_storage_bucket.this
```
and then import it back
```
$ terraform import 'module.storage-test["infra-test-bucket"].yandex_storage_bucket.this' infra-test-bucket-nogbluzj
```
then I've got an error
`error getting storage client: failed to get default storage client`

How can I work around this problem?

**Comment by matveitkachenko** [comment]
> Hi I have a same question: if I remove the bucket from the terraform state like this
> 
> ```
> $ terraform state list
> module.storage-test["infra-test-bucket"].data.aws_iam_policy_document.this[0]
> module.storage-test["infra-test-bucket"].data.yandex_client_config.client
> module.storage-test["infra-test-bucket"].random_string.unique_id
> module.storage-test["infra-test-bucket"].yandex_iam_service_account.storage_admin[0]
> module.storage-test["infra-test-bucket"].yandex_iam_service_account_static_access_key.storage_admin[0]
> module.storage-test["infra-test-bucket"].yandex_resourcemanager_folder_iam_member.storage_admin[0]
> module.storage-test["infra-test-bucket"].yandex_storage_bucket.this
> ```
> 
> and then import it back
> 
> ```
> $ terraform import 'module.storage-test["infra-test-bucket"].yandex_storage_bucket.this' infra-test-bucket-nogbluzj
> ```
> 
> then I've got an error `error getting storage client: failed to get default storage client`
> 
> How can I work around this problem?

Did you solve the problem?

**Comment by KoDA82** [comment]
Should be fixed within the next release
