### ISSUE TITLE
Secondary Disk Specification for Compute Group

### ISSUE THREAD

**Issue by daskol** [yandex-cloud/terraform-provider-yandex#123]
It would be great to create compute disks separately with `count` meta var and then attach a list of these newly created disks as secondary disks to group of instances. Here is an example below.
```hcl
resource "yandex_compute_disk" "volume" {
  count = 3
}

resource "yandex_compute_instance_group" "group" {
  instance_template {
    secondary_disk {
      disk_ids = yandex_compute_disk.volume.*.id
    }
  }

  scale_policy {
    fixed_scale {
      size = 3
    }
  }
}
```

**Comment by apilikov** [comment]
Hello! Thanks for posting this!

It is by design that the disk id is equal for an instance group. You'll have to create 3 instance groups to achieve what you want.

Hope that helps.
