### ISSUE TITLE
Add sensitive flag for yandex_kms_secret_ciphertext

### ISSUE THREAD

**Issue by sadon** [yandex-cloud/terraform-provider-yandex#128]
It is not a good practive to write out cypher text to console within terraform plan/apply

Please  add sensitive flag for suitable data fields
https://github.com/yandex-cloud/terraform-provider-yandex/blob/master/yandex/resource_yandex_kms_secret_ciphertext.go

https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/schema#Schema.Sensitive

```
terrafrom plan
...
  # module.yandex_kms_secret_ciphertext.ca_pem will be created
  + resource "yandex_kms_secret_ciphertext" "ca_pem" {
      + ciphertext = (known after apply)
      + id         = (known after apply)
      + key_id     = "abjkhsk8ddertodkkv0t"
      + plaintext  = <<-EOT
            SECRET VALUES WRITE OUT to a display

```

**Comment by ayza11** [comment]
> It is not a good practive to write out cypher text to console within terraform plan/apply

I believe you mean "write out plain text (of a secret)" by this. Sounds reasonable.

**Comment by ayza11** [comment]
Hi, did I get you correct - you mean hide a ciphertext? Ciphertext in fact is not a sensitive data. Or you mean it takes too much space on the screen?

**Comment by sadon** [comment]
> Hi, did I get you correct - you mean hide a ciphertext? Ciphertext in fact is not a sensitive data. Or you mean it takes too much space on the screen?

No, I mean to hide _plaintext_ field (at least from screen)

**Comment by ayza11** [comment]
Ok, sounds reasonable.
