### ISSUE TITLE
[vpc subnets] add NAT flag

### ISSUE THREAD

**Issue by misterkramer** [yandex-cloud/terraform-provider-yandex#129]
Hi! It would be cool to be able to enable NAT for subnet via terraform - https://cloud.yandex.com/docs/vpc/operations/enable-nat

**Comment by theigel** [comment]
Thanks for the request!

It's on the VPC team's backlog; having an interested user will help us to keep priority higher.

**Comment by Wolfeg** [comment]
we use that function. making it by "hands" not so good

**Comment by zorgzerg** [comment]
Please, guys. Very need

**Comment by bogi0704** [comment]
Hi guys, we also need this feature.

**Comment by jluenne** [comment]
Please add this feature, we really need it.

**Comment by ekarazhas** [comment]
+1 for this change!

**Comment by victoriavoss96** [comment]
I concur, we really need it.

**Comment by ArturAmpilogov** [comment]
Pushing to top  :rocket:

It is a very important feature.

**Comment by saikatharryc** [comment]
lining up!

**Comment by Sebor** [comment]
Any news about this issue?
BTW according to the [documentation](https://cloud.yandex.com/en-ru/docs/vpc/api-ref/Subnet/create) there is even no field for that within API :(

**Comment by morgulnet** [comment]
push to top ! +1

**Comment by Makerthone** [comment]
push to top ! + 1

**Comment by agl-nn** [comment]
+1

**Comment by degibenz** [comment]
+1

**Comment by zuevda** [comment]
+1

**Comment by k-popov** [comment]
Judging by data being sent when enabling via WebUI the API is ready to accept this option:

`'{"subnetId":"<REDACTED>","egressNatEnable":true,"updateMask":{"paths":["egress_nat_enable"]}}'`

But it's not mentioned in official API docs: https://cloud.yandex.ru/docs/vpc/api-ref/Subnet/create and also not described https://github.com/yandex-cloud/go-genproto/blob/master/yandex/cloud/vpc/v1/subnet.pb.go which is required to add the option to TF provider (which doesn't look complex from perspective of person not familiar with Golang).

**Comment by webngt** [comment]
+1

**Comment by akaGelo** [comment]
+1

**Comment by b2kos** [comment]
+1

**Comment by IgorGots** [comment]
Please add this feature.

**Comment by dnugmanov** [comment]
+1

**Comment by SlaySS** [comment]
+1

**Comment by k-popov** [comment]
Looks like this is not going to be implemented as the NAT flag is deprecated in favor of NAT gateway:

https://cloud.yandex.ru/docs/vpc/operations/enable-nat
https://cloud.yandex.ru/docs/vpc/concepts/gateways#nat-gateway

**Comment by Wolfeg** [comment]
this issue can be closed, cause now we have `vpc_gateway` resource that works in combination with `vpc_route_table`
https://terraform-provider.yandexcloud.net/Resources/vpc_route_table
