### ISSUE TITLE
Cyclic dependency when creating static route to internal address of compute instance

### ISSUE THREAD

**Issue by alxrem** [yandex-cloud/terraform-provider-yandex#131]
Hello.

Looks like it is impossible to create static route to internal address of compute instance.

I should create instance to know its internal address.
To create instance I should create subnet before.
To create subnet with the route table I should know static route with its next hop.
To know next hop I should create instance.

Isn't so?

**Comment by apilikov** [comment]
Thanks for posting this!
Could you please provide a shortest possible example with expected and actual behaviors stated.

Thank you!

**Comment by alxrem** [comment]
I have infrastructure connected to subnet `cycle`.

```terraform
resource "yandex_vpc_network" "cycle" {}

resource "yandex_vpc_subnet" "cycle" {
  network_id     = yandex_vpc_network.cycle.id
  v4_cidr_blocks = ["10.10.0.0/24"]
  zone           = "ru-central1-a"
}
```

I want to connect infrastructure to private `10.99.0.0/24` network that is
accessible by VPN. I decide to deploy compute instance `vpn_gate` and configure
static route to private network over internal address of `vpn_gate`.

I describe required resources by manifest

```terraform
resource "yandex_vpc_network" "cycle" {}

resource "yandex_vpc_route_table" "cycle" {
  static_route {
    destination_prefix = "10.99.0.0/24"
    next_hop_address   = yandex_compute_instance.vpn_gate.network_interface.0.ip_address
  }
  network_id = yandex_vpc_network.cycle.id
}

resource "yandex_vpc_subnet" "cycle" {
  network_id     = yandex_vpc_network.cycle.id
  v4_cidr_blocks = ["10.10.0.0/24"]
  zone           = "ru-central1-a"
  route_table_id = yandex_vpc_route_table.cycle.id
}

resource "yandex_compute_instance" "vpn_gate" {
  network_interface {
    subnet_id = yandex_vpc_subnet.cycle.id
  }
  boot_disk {}
  resources {
    cores  = 2
    memory = 2
  }
}
```

`terraform plan` reports error

> Error: Cycle: module.test_cycle.yandex_vpc_route_table.cycle, module.test_cycle.yandex_vpc_subnet.cycle, module.test_cycle.yandex_compute_instance.vpn_gate

**Comment by alxrem** [comment]
The cycle could be avoided if the static route could be defined as a separate resource f.e.

```terraform
resource "yandex_vpc_network" "cycle" {}

resource "yandex_vpc_route_table" "cycle" {
  network_id = yandex_vpc_network.cycle.id
}

resource "yandex_vpc_subnet" "cycle" {
  network_id     = yandex_vpc_network.cycle.id
  route_table_id = yandex_vpc_route_table.cycle.id
}

resource "yandex_compute_instance" "vpn_gate" {
  network_interface {
    subnet_id = yandex_vpc_subnet.cycle.id
  }
}

resource "yandex_vpc_static_route" "vpn" {
  route_table_id = yandex_vpc_route_table.cycle.id

  destination_prefix = "10.99.0.0/24"
  next_hop_address   = yandex_compute_instance.vpn_gate.network_interface.0.ip_address
}
```

**Comment by apilikov** [comment]
Thanks for reaching out. We'll take some time to assess the issue.

**Comment by raorn** [comment]
Static route as separate resource is not available ATM, but we'll thing about breaking such cycles.

For now you can use specific `ip_address` when creating instance. Like:

```
resource "yandex_vpc_route_table" "cycle" {
  static_route {
    destination_prefix = "10.99.0.0/24"
    next_hop_address   = "10.10.0.254"
  }
  network_id = yandex_vpc_network.cycle.id
}

resource "yandex_compute_instance" "vpn_gate" {
  network_interface {
    subnet_id = yandex_vpc_subnet.cycle.id
    ip_address   = "10.10.0.254"
  }
  boot_disk {}
  resources {
    cores  = 2
    memory = 2
  }
}
```

**Comment by apilikov** [comment]
If you need additional help please reopen the issue or file a new one. Thank you!
