### ISSUE TITLE
[managed k8s] add security group management for nodes

### ISSUE THREAD

**Issue by misterkramer** [yandex-cloud/terraform-provider-yandex#139]
subj
Now we add SG through the cli

**Comment by apilikov** [comment]
Try using the latest terraform provider. The requested feature is already released.

**Comment by misterkramer** [comment]
Exactly! the day before there was a release on March 10th - https://github.com/yandex-cloud/terraform-provider-yandex/blob/master/CHANGELOG.md#0520-march-10-2021
Thanks!
I close this issue then.
