### ISSUE TITLE
Provide a way to get default folder id from provider config

### ISSUE THREAD

**Issue by Nyoroon** [yandex-cloud/terraform-provider-yandex#14]
Folder ID (and Cloud ID) is required in provider config:
```
provider "yandex" {
  cloud_id                 = "cloud_id_here"
  folder_id                = "folder_id_here"
}
```
For some resources it's required to specify folder id (like for instance_group, why?) or to get image from non-"standard-images" directory it would be useful to get default folder id from provider config.

**Comment by GennadySpb** [comment]
Hi @Nyoroon !

You are right attribute requirement for IG looks redundant, will be fixed.

**Comment by GennadySpb** [comment]
@Nyoroon 
so, fixed in 0.8.2.

**Comment by GennadySpb** [comment]
Regarding the issue of the date source for image, in my opinion the behavior using `standard-images` as implicit default value for `folder_id` to look up latest image satisfies most of the needs.

@Nyoroon Could you explain your point of view about `data "yandex_compute_image" ...` ?

**Comment by Nyoroon** [comment]
@GennadySpb We build our own images with packer and set specific image-family, so terraform can pick up most fresh image to update instance-group. To use that feature we need to specify our own folder id in two places (provider and image data source).

**Comment by GennadySpb** [comment]
Why not just use variable with value of needed folder_id?
In both (or any other) places: provider config and image data source.
