### ISSUE TITLE
Error while creating DNS records via Terraform

### ISSUE THREAD

**Issue by pabloli84** [yandex-cloud/terraform-provider-yandex#140]
Hi,

Terraform version: 0.14
Yandex provider version: 0.52.0

While creating DNS records with Terraform an error appears:

> Error: Provider produced inconsistent result after apply
> 
> When applying changes to yandex_dns_recordset.master[1], provider
> "registry.terraform.io/yandex-cloud/yandex" produced an unexpected new value:
> Root resource was present, but now absent.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.
> 
> 
> Error: Provider produced inconsistent result after apply
> 
> When applying changes to yandex_dns_recordset.master[0], provider
> "registry.terraform.io/yandex-cloud/yandex" produced an unexpected new value:
> Root resource was present, but now absent.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.
> 
> 
> Error: Provider produced inconsistent result after apply
> 
> When applying changes to yandex_dns_recordset.master[2], provider
> "registry.terraform.io/yandex-cloud/yandex" produced an unexpected new value:
> Root resource was present, but now absent.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.

Detailed log is attached.

Terraform code that causes the error:

```
resource "yandex_dns_recordset" "master" {
  count = var.okd_kube_master_num
  zone_id = yandex_dns_zone.okd-cluster.id
  name    = element(yandex_compute_instance.master.*.name, count.index)
  type    = "A"
  ttl     = 300
  data    = [element(yandex_compute_instance.master.*.network_interface.0.ip_address, count.index)]
}

```

Though DNS records are actually created, terraform state is not updated and on second run terraform tries to create these records again, and this time fails, because records already exist.

This error is reproduced with a single record as well (without _count_).

Please check this problem.

Thanks!

[tf.log.zip](https://github.com/yandex-cloud/terraform-provider-yandex/files/6131968/tf.log.zip)

**Comment by kdudkov** [comment]
Error happens only if short recordset name is used (without '.' at the end). Will be fixed shortly.

**Comment by pabloli84** [comment]
> Error happens only if short recordset name is used (without '.' at the end). Will be fixed shortly.

Thanks! I can confirm that with FQDN it works well!

**Comment by kdudkov** [comment]
fixed
