### ISSUE TITLE
bucket error: failed to get default storage client 

### ISSUE THREAD

**Issue by romcheck** [yandex-cloud/terraform-provider-yandex#144]
The issue is very similar to #121.

But it occurs after importing bucket into terraform state and run `plan` command even when `access_key` and `secret_key` are present in bucket resource definition:

```
resource "yandex_storage_bucket" "bucket" {
  bucket = "bucket_name_value"
  access_key = "access_key_value"
  secret_key = "secret_key_value"
}
```

And it only works when `storage_access_key` and `storage_secret_key` are resent on `provider` definition:

```
provider "yandex" {
  folder_id = local.global_tfsettings.catalog
  storage_access_key = "access_key_value"
  storage_secret_key = "secret_key_value"
}
```

Terraform does not allow evaluation on `provider` definition. So it is not an appropriate workaround unfortunate.

Provider version is 0.54.0.
Terraform version is 0.14.9.

**Comment by Wolfeg** [comment]
i've fixed that by moving key and secret from bucket to provider section. or you use different keys for different buckets (not similar with that you provide in provider)?

**Comment by romcheck** [comment]
> i've fixed that by moving key and secret from bucket to provider section. or you use different keys for different buckets (not similar with that you provide in provider)?

Yes. I use parameterised values for storage_access_key and storage_access_key.

**Comment by apilikov** [comment]
Thanks for reaching out. Could you please provide a reproducible example we would be able to try out. Thank you!

**Comment by apilikov** [comment]
Closing the issue as there are no updates for a long time.
