### ISSUE TITLE
Изменение имени загрузочного диска триггерит пересоздание ВМ

### ISSUE THREAD

**Issue by Wolfeg** [yandex-cloud/terraform-provider-yandex#146]
если изменить в секции
```
boot_disk {
    initialize_params {
      name     = "example-name"
      size     = 60
      type     = "network-hdd"
      image_id = var.image_id
    }
  }
```
имя диска, то план показывает, что необходимо пересоздание ВМ, при этом имя диска можно спокойно поменять через веб "Консоль" без пересоздания, и план уже не ругается на смену имени.

**Comment by apilikov** [comment]
Спасибо за обращение. Блок initialize_params является параметрами используемыми только при создании загрузочного диска для новой ВМ. Таким образом их изменение приводит к пересозданию ВМ. Такова цена концепции immutable. Сейчас в разработке находится задача о возможности изменения как загрузочного так и дополнительного дисков при помощи terraform. Однако для этого потребуется создавать диски при помощи ресурса yandex_compute_disk.
