### ISSUE TITLE
object storage: configure website redirect

### ISSUE THREAD

**Issue by AlexElin** [yandex-cloud/terraform-provider-yandex#149]
Describe in the docs how to configure website redirect using the provider

This functionality is available via a UI console
![redirect](https://user-images.githubusercontent.com/13061803/113691286-f0ac7800-96d4-11eb-84d7-ad168c3458e0.jpg)

**Comment by apilikov** [comment]
Thank for posting this. You'll be notified once this is resolved.

**Comment by apilikov** [comment]
The issue has been resolved recently. Feel free to reopen if the problem is still there. Thank you!
