### ISSUE TITLE
Yandex.DNS support

### ISSUE THREAD

**Issue by eill** [yandex-cloud/terraform-provider-yandex#15]
Hello, do you have any plans of implementing the Yandex DNS (pdd.yandex.ru and connect.yandex.ru) support in terraform?

It would be very useful for people who use the yandex.connect and yandex.dns services.

Thanks in advance.

**Comment by alexanderKhaustov** [comment]
Hi
This is currently outside the scope of the provider and there are no plans for such support

**Comment by eill** [comment]
ok, will you merge this functionality to upstream if someone (maybe I) will implement it?

**Comment by GennadySpb** [comment]
@eill Hi! Yandex Connet (_pdd.yandex.ru_ and _connect.yandex.ru_) is a separate service that belongs to Yandex [family of services](https://yandex.ru/all).

Scope of this provider is Yandex.Cloud service only.

Terraform has [reference](https://www.terraform.io/docs/providers/type/community-index.html) of community supported providers. Also you could fill out form and submit your provider.

**Comment by unixzen** [comment]
Hello! At last release (https://github.com/go-acme/lego/releases/tag/v3.7.0) of lego acme library implemented yandex dns provider, but at page nothing updates https://www.terraform.io/docs/providers/acme/index.html
