### ISSUE TITLE
object-storage: describe how to specify max size

### ISSUE THREAD

**Issue by AlexElin** [yandex-cloud/terraform-provider-yandex#151]
Describe in the docs how to specify max size.
Here how it looks in the UI console
![max_size](https://user-images.githubusercontent.com/13061803/113758487-9afbbe00-971c-11eb-8edd-7f9bbb432762.jpg)

**Comment by apilikov** [comment]
Thank for posting this. You'll be notified once this is resolved.

**Comment by ferux** [comment]
Hi, @AlexElin 
We are happy to introduce you our new grpc API for Object storage, which allows you to set max size for bucket and not only this. 
This could be done by using [Update](https://cloud.yandex.com/en/docs/storage/api-ref/grpc/bucket_service#Update) method for existing buckets and [Create](https://cloud.yandex.com/en/docs/storage/api-ref/grpc/bucket_service#Create) method for new buckets.

For more information of how to use this api, please, follow this link: https://cloud.yandex.com/en/docs/storage/api-ref/grpc/

**Comment by AlexElin** [comment]
The instruction https://cloud.yandex.com/en/docs/storage/operations/buckets/limit-max-volume
