### ISSUE TITLE
max_memory_usage: must be a whole number

### ISSUE THREAD

**Issue by bryzgaloff** [yandex-cloud/terraform-provider-yandex#152]
I try to limit memory used by ClickHouse query via https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/mdb_clickhouse_cluster#max_memory_usage. The desired limit is 7 GiB:

```
  user {
    name = …
    password = …
    permission { database_name = … }
    settings {
      max_memory_usage = 7516192768
    }
  }
```

When executing `terraform plan` with this setting, I encounter an issue: `user.2.settings.0.max_memory_usage: must be a whole number, got 7.516192768e+09`

Looks like number is converted to float because it exceeds int limits. How can I overcome this? The number itself is valid and can be set through UI.

Btw probably not a right place to ask, but question is related: why is this a user setting? Should not it be server-wide? Or is ClickHouse now able to limit memory usage on a per-user basis?

**Comment by apilikov** [comment]
Thanks for posting this. Currently you can't overcome this. We have to change the provider code to solve this. Stay tuned.

**Comment by GrigoryPervakov** [comment]
Could you write your `terraform version` output?

About your question: Yes, this setting applies only to queries that this user runs.

**Comment by bryzgaloff** [comment]
> Could you write your `terraform version` output?

```bash
$ terraform version
Terraform v0.13.6
```

> About your question: Yes, this setting applies only to queries that this user runs.

Thank you. In fact this is a more complicated topic I have been consulted by Yandex.Cloud support :) For the ones looking for details, here they are:
- `max_memory_usage` ([docs](https://clickhouse.tech/docs/en/operations/settings/query-complexity/#settings_max_memory_usage)) is a per-query per-user memory limit. One query by a user cannot allocate more memory than this limit.
- `max_memory_usage_for_user` is a per-user memory limit that limits all the parallel queries run by user.
- `max_server_memory_usage` ([docs](https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#max_server_memory_usage)) is a per-server memory limit that limits all the parallel queries run by all the users. This is set automatically and is expected to be set with some margin to guaranteedly avoid server death. however, in my personal case server could go down but this looks like a miscongifuration.

**Comment by GrigoryPervakov** [comment]
You should try to update your terraform version.
On 0.15.1 works well https://pastebin.com/UhkhGBXh

**Comment by apilikov** [comment]
Do you experience any troubles regarding the issue?

**Comment by bryzgaloff** [comment]
Have not had an opportunity to try it out unfortunately. Will probably do it little bit later. Maybe this week. Will definitely let you know the outcome regardless of success.

**Comment by bryzgaloff** [comment]
Thank you guys for your help, it worked for me.

What have I done:
* Removed `settings` configuration from user as I was initially using the version of Terraform that did not support it. My version of Terraform was 0.12.
* Step-by-step downloaded 0.13, 0.14 and 0.15 and run `terraform apply` for every newly downloaded version without making any changes to the `*.tf` file. This is required by the Terraform update guides. When updated to 0.14, preliminary `terraform init` call was required to install Yandex Cloud plugin.
* Finally added `settings` section with `max_memory_usage_for_user` and successfully run `terraform apply` with 0.15.5 version.

I am closing the issue as it is resolved now.
