### ISSUE TITLE
[minor chore] add changelog  to the release page

### ISSUE THREAD

**Issue by misterkramer** [yandex-cloud/terraform-provider-yandex#154]
It would be convenient to immediately see the changelog on the release page when releasing a release, here - https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.55.0

For example, it is convenient to watch from a mobile device if you are subscribed to releases.

**Comment by apilikov** [comment]
Thanks for reaching out. We'll do this, no problem.

**Comment by misterkramer** [comment]
@apilikov the release description is missing again(

**Comment by apilikov** [comment]
We are sorry, it's a human mistake.

**Comment by misterkramer** [comment]
> We are sorry, it's a human mistake.

Give power to the robots😊
