### ISSUE TITLE
Failed to query available provider packages

### ISSUE THREAD

**Issue by igkuz** [yandex-cloud/terraform-provider-yandex#157]
Installed the fresh version of terraform for MacOS.
```
$ terraform -version
Terraform v0.15.0
on darwin_amd64
```

Followed the instructions from [Yandex Cloud docs](https://cloud.yandex.ru/docs/solutions/infrastructure-management/terraform-quickstart#configure-provider) & [Terraform provider docs](https://cloud.yandex.ru/docs/solutions/infrastructure-management/terraform-quickstart#configure-provider)

created main.tf
```
provider "yandex" {
  token                    = "auth_token_here"
  cloud_id                 = "cloud_id_here"
  folder_id                = "folder_id_here"
  zone                     = "ru-central1-a"
}
```

and got a error

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/yandex...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/yandex: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/yandex
│
│ Did you intend to use yandex-cloud/yandex? If so, you must specify that source address in each module which requires that provider. To see which modules are currently
│ depending on hashicorp/yandex, run the following command:
│     terraform providers
```

Fixed with adding to main.tf:
```
terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
    }
  }
}
```

Is it by design? If so, then it would cool to add those lines to the docs. If not, what am I doing wrong?

**Comment by apilikov** [comment]
Thanks for reaching out! We are aware of the issue and the fix is under way. Stay tuned.

**Comment by apilikov** [comment]
We've updated the docs. Please feel free to reopen the issue in case you encounter any similar problems.
