### ISSUE TITLE
Impossible to define configuration with nat instance

### ISSUE THREAD

**Issue by subuk** [yandex-cloud/terraform-provider-yandex#167]
Configuration following [nat instance](https://cloud.yandex.ru/docs/solutions/routing/nat-instance) tutorial leads to cycle dependencies error:

```
Error: Cycle: yandex_vpc_subnet.office_az1, yandex_compute_instance.bastion, yandex_vpc_route_table.main
```

## How to reproduce

Create the following configuration, try to apply and get the error:

```
terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
    }
  }
}

provider "yandex" {
  cloud_id  = "..."
  folder_id = "..."
}

resource "yandex_vpc_network" "main" {
  name = "main"
}

resource "yandex_vpc_route_table" "main" {
  network_id = yandex_vpc_network.main.id

  static_route {
    destination_prefix = "0.0.0.0/0"
    next_hop_address   = yandex_compute_instance.bastion.network_interface.0.ip_address
  }
}

resource "yandex_vpc_subnet" "office_az1" {
  v4_cidr_blocks = ["10.105.1.0/24"]
  zone           = local.zone.az1
  network_id     = yandex_vpc_network.main.id
  route_table_id = yandex_vpc_route_table.main.id
}

resource "yandex_compute_instance" "bastion" {
  name        = "bastion"
  platform_id = "standard-v2"
  zone        = local.zone.az1

  resources {
    cores  = 2
    memory = 2
    core_fraction = 20
  }

  boot_disk {
    initialize_params {
      image_id = local.centos_8_image_id
      size = 10
    }
  }
  network_interface {
    subnet_id = yandex_vpc_subnet.office_az1.id
  }
}
```

## How to fix

For example AWS provider has separate [route_table_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table_association) resource.

Maybe I missed something and this configuration can be fixed another way?

**Comment by GennadySpb** [comment]
Hi @subuk ! 
Ugly hack: try to use fixed (predefined) IP address for the NAT instance and target for the next hop. This will break the cycle dependency.

**Comment by subuk** [comment]
Yeah, in the end I did it this hacky way :)

**Comment by apilikov** [comment]
Do you have any troubles regarding the issue?

**Comment by subuk** [comment]
It would be great to have a way to assign a dynamic internal ip address to the host used in static routes. But the fixed ip address method is good enough, so, my problem solved.
