### ISSUE TITLE
yandex_kubernetes_node_group.maintenance_window change diff

### ISSUE THREAD

**Issue by pit** [yandex-cloud/terraform-provider-yandex#168]
When you set maintenance_window parameters via terraform and later run apply again you receive diff here due to different values formatting:
```
-/+ resource "yandex_kubernetes_node_group" "this" {
...
    maintenance_policy {
          + maintenance_window {
              + duration   = "2h"
              + start_time = "05:00"
            }
          - maintenance_window {
              - duration   = "2h0m0s" -> null
              - start_time = "05:00:00.000000000" -> null
            }
    }
```

**Comment by apilikov** [comment]
Thanks for reaching out! I can't confirm the issue using the latest provider. Could you please provide a minimal possible example for us to try. Thank you!

**Comment by pit** [comment]
Will add minimal example later this week.

**Comment by apilikov** [comment]
Do you still experience the issue? Thank you!

**Comment by apilikov** [comment]
Closing the issue as there have been no updates for a while.
