### ISSUE TITLE
Please add port to yandex_mdb_postgresql_cluster attributes

### ISSUE THREAD

**Issue by pit** [yandex-cloud/terraform-provider-yandex#169]
Still you have port number fixed for now, it could be very useful to have that number in resource attributes as constant so developers wiil be abble to add it to terraform module output. Without it you need to go to documentation to get port number.

**Comment by apilikov** [comment]
Thanks for reaching out. We accept the proposal. If you wish to resolve it faster you can try contributing the solution to the project.

**Comment by apilikov** [comment]
Unfortunately the port cannot be changed. It has been stated explicitly in the docs recently.
