### ISSUE TITLE
Specify cloud_id in yandex_resourcemanager_folder datasource

### ISSUE THREAD

**Issue by asterix201** [yandex-cloud/terraform-provider-yandex#17]
I'm trying to get IDs for resources from data sources (to provide easier code readability) by resource name.
And it is not possible to get information about a folder without specifying clout_id in provider configuration. 
I.e. my idea to setup configuration like this: 
```
provider "yandex" {
  token = "${var.token}"
}

data "yandex_resourcemanager_cloud" "my_cloud" {
  name = "${var.cloud_name}"
}

data "yandex_resourcemanager_folder" "my_folder" {
  name = "folder_name"
}

```
And then use variables: 
cloud_id = "${data.yandex_resourcemanager_cloud.my_cloud.id}"
folder_id  = "${data.yandex_resourcemanager_folder.my_folder.id}"

But this way does not work, as I receive an error: 
```
Error: Error refreshing state: 1 error occurred:
        * data.yandex_resourcemanager_folder.my_folder: 1 error occurred:
        * data.yandex_resourcemanager_folder.my_folder: data.yandex_resourcemanager_folder.my_folder: failed to resolve data source folder by name: failed to find folder with name "folder_name": request-id = db77cb01-6527-4623-8f64-4a6be4292773 rpc error: code = InvalidArgument desc = cloudId: String value is too short
```

I'm not able to specify cloud_id variable for the data source. It needs to be set in the provider configuration. 
And this behavior looks strange and incorrect.

**Comment by GennadySpb** [comment]
Hello! 
In version 0.10.0 would be possible to specify `cloud_id` in data source `yandex_resourcemanager_folder`.

[See all planned changes](https://github.com/terraform-providers/terraform-provider-yandex/blob/master/CHANGELOG.md#0100-unreleased).

**Comment by GennadySpb** [comment]
Provider version `0.10.0` just released.
