### ISSUE TITLE
yandex_mdb_postgresql_cluster: pg_hint_plan_enable_hint cannot be changed without using pg_hint_plan in shared_preload_libraries

### ISSUE THREAD

**Issue by Ranger-X** [yandex-cloud/terraform-provider-yandex#170]
Пытаюсь обновить кластер PG 12 с включенной библиотекой pg_hint_plan, но получаю ошибку: **rpc error: code = InvalidArgument desc = pg_hint_plan_enable_hint cannot be changed without using pg_hint_plan in shared_preload_libraries**.

При этом все нужные параметры заданы. Вот часть манифеста:
```
    postgresql_config = {
       shared_preload_libraries            = "SHARED_PRELOAD_LIBRARIES_PG_HINT_PLAN"
       ...
      pg_hint_plan_enable_hint           = true
      pg_hint_plan_enable_hint_table = true
      pg_hint_plan_debug_print          = "PG_HINT_PLAN_DEBUG_PRINT_ON"
      pg_hint_plan_message_level     = "LOG_LEVEL_NOTICE"
       ...
   }
```
Т.е. библиотека добавлена в shared_preload_libraries, но почему-то провайдер (или Cloud API?) ее "не видит".

**Comment by apilikov** [comment]
The issue has been resolved recently. Feel free to reopen if the problem is still there. Thank you!
