### ISSUE TITLE
Error adding new hosts to Redis cluster

### ISSUE THREAD

**Issue by onurguzel** [yandex-cloud/terraform-provider-yandex#180]
**Issue description:**
Terraform fails to update Redis cluster with new hosts.

**Expected behavior:**
Terraform should create new hosts in the cluster

**Actual behavior:**
Terraform receives an error from API: "No changes detected"

**Provider version:**
0.61.0

**Terraform output:** (Actual resource IDs are omitted for privacy)
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.cluster.yandex_mdb_redis_cluster.redis[0] will be updated in-place
  ~ resource "yandex_mdb_redis_cluster" "redis" {
        id                 = "c9q6...fgmk"
        name               = "redis-001"
        # (10 unchanged attributes hidden)

      + host {
          + subnet_id = "e2l7...dpjs"
          + zone      = "ru-central1-b"
        }
      + host {
          + subnet_id = "b0c6...iscc"
          + zone      = "ru-central1-c"
        }

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.cluster.yandex_mdb_redis_cluster.redis[0]: Modifying... [id=c9q6...fgmk]

│ Error: Error while requesting API to update Redis Cluster "c9q6...fgmk": rpc error: code = InvalidArgument desc = No changes detected
```

**Comment by apilikov** [comment]
Thanks for reaching out. We'll investigate and get back to you. Stay tuned!

**Comment by apilikov** [comment]
Unfortunately we can't reproduce the issue ourselves. Could you please provide a shortest possible example which can reproduce the issue. Thank you!

**Comment by onurguzel** [comment]
> Unfortunately we can't reproduce the issue ourselves. Could you please provide a shortest possible example which can reproduce the issue. Thank you!

Thanks for investigating this issue. Unfortunately I no longer work with Yandex Cloud and I cannot check this issue can be reproduced or not. You can close the issue if you want.

Best regards,

**Comment by Apelsin234** [comment]
Hello! Thank you for reporting the issue. Unfortunately, we were unable to reproduce the problem.
