### ISSUE TITLE
Error in data.yandex_kubernetes_node_group

### ISSUE THREAD

**Issue by alyabievgy** [yandex-cloud/terraform-provider-yandex#182]
`terraform show` returns:
`network_acceleration_type = "type_unspecified"`
but expected to be one of ["standard", "software_accelerated"]

`terraform show`  for `resource "yandex_kubernetes_node_group"` does the same
```
Terraform v1.0.3 on linux_amd64
+ provider registry.terraform.io/yandex-cloud/yandex v0.61.0
```

**Comment by apilikov** [comment]
type_unspecified is a special default value that you cannot set yourself. So this is by design. Does it cause any troubles to you?

**Comment by apilikov** [comment]
Closing the issue as there are no updates for a long time.
