### ISSUE TITLE
yandex_mdb_postgresql_cluster labels with capital letters

### ISSUE THREAD

**Issue by vterdunov** [yandex-cloud/terraform-provider-yandex#185]
```
labels: Symbol 'P' not allowed in value.
```

`yandex_mdb_postgresql_cluster` fails with the error if a label (key or value) has a capital letter or any space. Provider versions: 0.61.0
Example of not valid labels:
```
  labels = {
    Project     = "My Cool Project"
    Environment = "Prod"
  }
 ```

**Comment by GennadySpb** [comment]
Hi @vterdunov !
There is restriction by design for label attr. Check [doc](https://cloud.yandex.com/en-ru/docs/managed-postgresql/api-ref/grpc/cluster_service#CreateClusterRequest):
 

> Custom labels for the PostgreSQL cluster as key:value pairs. Maximum 64 per resource. For example, "project": "mvp" or "source": "dictionary". No more than 64 per resource. The maximum string length in characters for each value is 63. Each value must match the regular expression [-_0-9a-z]*. The maximum string length in characters for each key is 63. Each key must match the regular expression [a-z][-_0-9a-z]*

**Comment by vterdunov** [comment]
Thanks @GennadySpb !
I guess it would better to be consistent with other YC resources. Some of them (e.g. [vpc](https://cloud.yandex.com/docs/vpc/api-ref/grpc/network_service#Network2)) allows to add labels with capital letters.
At lest it would awesome to return more useful error with will print the regex.
Last but not least, the [TF doc](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/mdb_postgresql_cluster#labels) from registry doesn't tell anyting about the restriction.

**Comment by apilikov** [comment]
Is there anything left unresolved in the issue? @vterdunov

**Comment by apilikov** [comment]
Closing the issue as there have been no updates for a while.
