### ISSUE TITLE
Add Yandex Cloud CDN resource and data source to the provider

### ISSUE THREAD

**Issue by flaksp** [yandex-cloud/terraform-provider-yandex#188]
https://cloud.yandex.ru/services/cdn

**Comment by apilikov** [comment]
Thanks for reaching out. We'll let you know once the feature is implemented.

**Comment by hexagon141** [comment]
Is there any update?

**Comment by max-arnold** [comment]
@apilikov Скажите, а планируется как-то организовать работу с тикетами на Github? CDN ресурс [реализован](https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.69.0) в декабре 2021, а тикет никто не закрыл...

Аналогичная ситуация вот с этой фичей https://github.com/yandex-cloud/terraform-provider-yandex/issues/377

**Comment by KoDA82** [comment]
> @apilikov Скажите, а планируется как-то организовать работу с тикетами на Github? CDN ресурс [реализован](https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.69.0) в декабре 2021, а тикет никто не закрыл...
> 
> Аналогичная ситуация вот с этой фичей #377

привет! для новых issue и PRs организован процесс их обработки
все старые планируем разобрать до конца этого года
@apilikov более за этот провайдер не отвечает
