### ISSUE TITLE
yandex_kubernetes_node_group does not allow to specify placement group

### ISSUE THREAD

**Issue by kudrevatykh** [yandex-cloud/terraform-provider-yandex#189]
UI and API provide PlacementPolicy object, but terraform provider does not have such argument

**Comment by apilikov** [comment]
Try using `instance_template.placement_policy` attribute of `yandex_kubernetes_node_group`.

**Comment by kudrevatykh** [comment]
thanks, may be it should be documented?

**Comment by apilikov** [comment]
You are right. You'll get notified once the feature is resolved.

**Comment by apilikov** [comment]
The issue has been resolved recently. Feel free to reopen if the problem is still there. Thank you!
