### ISSUE TITLE
Object storage bucket resource

### ISSUE THREAD

**Issue by StupidScience** [yandex-cloud/terraform-provider-yandex#19]
Do you have any plans for object storage bucket resource? If yes can you please provide any ETA for it?

**Comment by GennadySpb** [comment]
Hi @StupidScience !
There are plans for terraform resources for Yandex Object Storage exist but without ETA  right now.

**Comment by GennadySpb** [comment]
@StupidScience 
I am pleased to announce that bucket support has been released [0.20.0](https://github.com/terraform-providers/terraform-provider-yandex/blob/master/CHANGELOG.md#0200-october-15-2019).

**Comment by StupidScience** [comment]
Thanks for info.
I'll give it a try.

**Comment by StupidScience** [comment]
@GennadySpb is there any way to give permissions for service accounts to buckets via terraform?

**Comment by GennadySpb** [comment]
@StupidScience right now you could use [acl](https://www.terraform.io/docs/providers/yandex/r/storage_bucket.html#acl) attribute to manage access to buckets.

**Comment by StupidScience** [comment]
@GennadySpb can't figure out how to grant bucket full control for service account. Can you pls provide an example?

**Comment by GennadySpb** [comment]
1) create folder
2) create SA within folder from first step
3) grant "editor" role to that SA
4) create bucket inside folder from first step

**Comment by StupidScience** [comment]
@GennadySpb with this approach you grant Editor role to folder not bucket. So you need one bucket per folder. Right?
But i need to add full control access for service account just to one bucket.
So it should be analog for 
```
aws --endpoint-url=https://storage.yandexcloud.net \
    s3api put-bucket-acl \
    --bucket mybucket \
    --grant-full-control id=myserviceaccountid
```

Also i see no options to define folder that bucket should belong to.

**Comment by StupidScience** [comment]
So, @GennadySpb, any suggestions?

**Comment by StupidScience** [comment]
Hi, @GennadySpb 
Any news here?

**Comment by alexanderKhaustov** [comment]
Hi
I'm afraid the cloud IAM model does not currently support separate access rights for anything more granular than a folder and there are no specific plans for such support.

**Comment by StupidScience** [comment]
This is already possible to do even with WebUI. And with aws-cli as well.
Why is it not possible to do via terraform?

**Comment by GennadySpb** [comment]
Hi @StupidScience !
I back with news: check [release](https://github.com/terraform-providers/terraform-provider-yandex/blob/master/CHANGELOG.md#0370-april-16-2020) `0.37.0`. There is support to manage custom ACL for buckets.

**Comment by StupidScience** [comment]
@GennadySpb great news.
I will give it a try during next week I hope

**Comment by StupidScience** [comment]
@GennadySpb I see no options to define folder that bucket should belong to. How is it configuring?

**Comment by GennadySpb** [comment]
@StupidScience so if you have created bucket then it is already belong to some folder. 

Or the bucket will belong to the same folder as the service account, the static access key of which used during the creation operation.

**Comment by aleksandrovpa** [comment]
When i try to assign permissions to new bucket for SA through the `grant`, `$ terraform validate` shows error `Unsupported block type`
```terraform
resource "yandex_storage_bucket" "test" {
  bucket        = "test"
  force_destroy = false
  grant {
    id          = yandex_iam_service_account.test
    permissions = ["FULL_CONTROL"]
  }
}

resource "yandex_iam_service_account" "test" {
  name        = "test"
  description = ""
}
```
What i'm doing wrong? I follow [this instruction](https://www.terraform.io/docs/providers/yandex/r/storage_bucket.html#using-acl-policy-grants)

**Comment by StupidScience** [comment]
@GennadySpb sorry for a long silence period.
We've tested bucket creation with grant and it works well.
However it is not so greatly convenient to have grant inside bucket resource. Especially when you have some grants to buckets for Users not for Service Accounts. So you have to specify all grants in bucket object to make it work.

**Comment by GennadySpb** [comment]
@StupidScience What a convenient way in your opinion?

**Comment by yuanlinios** [comment]
@StupidScience, I have the same requirement. Would you please share me an example on how to grant access to a service account inside the bucket resource? 

Thanks!

**Comment by apilikov** [comment]
Closing the issue as there is no updates for a long time.
