### ISSUE TITLE
yandex_api_gateway Bad field mask in update_mask field. Unknown field, path=spec

### ISSUE THREAD

**Issue by izedgo** [yandex-cloud/terraform-provider-yandex#192]
After changing yandex_api_gateway resource spec field:

Error: Error while requesting API to update Yandex Cloud API Gateway: server-request-id = d471dc59-d694-473d-b490-2a27fa4ee42a server-trace-id = e8d7a99819eb5764:c402b1ab18e3a5f6:e8d7a99819eb5764:1 client-request-id = 55ee8031-d031-457a-9bd0-8bf77de0a8c2 client-trace-id = 1fe573d0-5a4f-40a4-87e6-16be1e91348c rpc error: code = InvalidArgument desc = Bad field mask in update_mask field. Unknown field, path=spec.

**Comment by apilikov** [comment]
Could you please provide a minimal reproducing example so we can review the issue. Thank you!

**Comment by izedgo** [comment]
Ошибка происходит при любом обновлении поля spec (напрямую или в файле).

resource "yandex_api_gateway" "my-gateway" {
  name = "my-gateway"
  spec = "${file("openapi.yaml")}"
}

**Comment by apilikov** [comment]
I confirm the issue. You'll be notified once it is resolved. Thank you for reaching out.

**Comment by apilikov** [comment]
@izedgo Check out the latest provider release. It should be resolved.
