### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by bill-rich** [yandex-cloud/terraform-provider-yandex#2]
Hello! 

My name is Bill, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit 95b990b5ddb22df38ba765a3b4ef0501e37e1d84.

- [x] Resource names specified in `provider.go` should match with the files names for specific resources and data sources. For example, `yandex_iam_service_account_iam_binding` is defined by `ResourceIamBindingWithImport`, but that function and resource are in `resource_iam_binding.go`. I would recommend creating individual resource files for each of the composited resources, use a function that follows naming convention of the rest of the resource functions, and have that function return the combined schema. Then you can rename the files like `resource_iam_binding.go` and possibly move them into a folder where they won’t be confused with other resources and data sources.

- [x] Required attributes in the resource schema should be grouped at the top. This is just a convention we’ve used that makes it easier to find which are required easily.

- [x] Errors could be more descriptive to help with troubleshooting. For example, in `resource_yandex_compute_disk.go`, there are three errors that are all “Error creating disk: error”. The content of `error` may make it clear what the problem is, but it may be helpful to have the base be something like “error getting zone while creating disk: error”.

- [x] Run HCL through `terraform fmt` to make sure everything is formatted correctly.

- [x] Check that documentation matches the schema. There seem to be some inconsistencies on which items are required and which are optional. For example `compute_disk` `size` is required in the schema, but listed as optional in the documentation.

Please let me know if you have any questions or feedback on the comments so far. Once the first one about the file naming and grouping conventions is addressed, I'd like to give everything another look to see if any additional work is needed. Thanks for working together with me on this!

**Comment by GennadySpb** [comment]
Hello Bill!

My name is Gennady, I'm a developer of the 'Tools for management and development' team @ Yandex.Cloud.

Just commited 9411fc7fc7b76ae296f4f5beec61aefe605a3de3 to address your feedback outlined above. Please check this out.

**Comment by bill-rich** [comment]
Thanks for taking a look at the feedback @GennadySpb. It definitely looks like things are going in the right direction. I went back through and got you some more detailed feedback. Hopefully this should about cover all that is needed.


- [ ] The `resource_` prefix for filenames is usually reserved for items that will end up as Terraform resources. Just to avoid confusion can the `resource_iam_*.go` files either be renamed to things like `iam_binding.go` or be moved into the existing iam*.go files?

- [ ] This isn’t an action item for getting the provider approved, but once it has been accepted the installation instructions in the README should be updated as the provider will be able to be installed using `terraform init`.

- [ ] The Terraform code in the test files should be run through `terraform fmt` also. It doesn’t matter too much for users, but it helps keep the code more readable if anyone is contributing or troubleshooting. I also noticed it there are at least some still to be done in the docs. `resourcemanager_cloud_iam_binding.html.markdown` is the one I saw it in.

- [ ] config.go imports `github.com/yandex-cloud/go-sdk/pkg/requestid`, but that package doesn’t seem to exist and is not vendored.

- [ ] Exported functions should have a comment describing them in the format of ```// {function_name} does …```

- [ ] You should check that all attributes are read as expected in tests so that you can tell if a resource is 100% properly being read and updated. For example, in resource_yandex_iam_service_account_test.go, `description` is not being checked. There may be some cases where this isn’t necessary, but it is a good rule in general.

- [ ] Make sure that acceptance tests exist which exercise all the utilized create, read, update, delete, import functions. `resource_yandex_vpc_network_test.go` seems to only run a basic vpc network creation.

- [ ] In the `yandex_compute_disk` resource, are `image_id`, `source_image_id`, `snapshot_id`, and `source_snapshot_id` all needed? From the docs, it sounds like they are the same but the `source_*` is read only.

- [ ] In the `yandex_compute_instance` resource, it doesn’t look like `instance_id` is necessary since the Id of the resource is the same. If that data is needed to be referenced in the Terraform config, `yandex_compute_instance.instance_name.id` can be used instead.

- [ ] The format of the import documentation isn’t consistent. In some cases the Id says something like “instance_id” and in others “{{id}}” is used. Either is fine, but it should be kept consistent.

- [ ] `iam_service_account_iam.html.markdown` should be split into three separate pages. One for each of the `iam_service_account_iam_*` resources listed on the page.

- [ ] The title on `iam_service_account_key.html.markdown` is incorrectly `yandex_service_account_key`. It should be `yandex_iam_service_account_key` to match the resource.

- [ ] You may want to use `sensitive` in your schema for `yandex_iam_service_account_key.secret_key`. It will still exist in state and will be able to be referenced elsewhere, but its contents will not be included in regular output or logs.

- [ ] It looks like some of the data sources only accept an ID as an argument. This is ok, but you might want to look into supporting for human readable options such as `name` to make the data sources more user friendly. In other providers, data sources are often used as a way to take the human readable option and find the less friendly bits of data like the ID.

**Comment by GennadySpb** [comment]
Thanks for the detailed feedback. New changes arrived according to the indicated remarks.

>   * This isn’t an action item for getting the provider approved, but once it has been accepted the installation instructions in the README should be updated as the provider will be able to be installed using `terraform init`.

I checked some other providers' README and did not get an idea of the specific conditions that should be mentioned about using `terraform init`.



>   * It looks like some of the data sources only accept an ID as an argument. This is ok, but you might want to look into supporting for human readable options such as `name` to make the data sources more user friendly. In other providers, data sources are often used as a way to take the human readable option and find the less friendly bits of data like the ID.


Implementing support for the attribute "name" in the data sources and resources in our near plans.

**Comment by bill-rich** [comment]
> I checked some other providers' README and did not get an idea of the specific conditions that should be mentioned about using `terraform init`.
You already have it correct. Sorry about that. Seems that I just misread something the first time.

Thank you for taking the time to address all the action items I brought up. It looks to me like your provider is ready to go! I'll let @cgriggs01 know.

**Comment by GennadySpb** [comment]
@cgriggs01 @bill-rich Thank you!
