### ISSUE TITLE
Syntax error in documentation

### ISSUE THREAD

**Issue by kurmanovd** [yandex-cloud/terraform-provider-yandex#203]
[Yandex_vpc_security_group_rule \ Example Usage](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/vpc_security_group_rule#example-usage)

Error in word "blocks": 

```v4_cidr_blokcs         = ["10.0.1.0/24", "10.0.2.0/24"]```

**Comment by apilikov** [comment]
Thank you very much for reaching out! You'll get notified once the issue is resolved.
If you wish to contribute it would be highly appreciated!

**Comment by kurmanovd** [comment]
@apilikov #208
