### ISSUE TITLE
Broken hosts in managed PostgreSQL

### ISSUE THREAD

**Issue by k0t3n** [yandex-cloud/terraform-provider-yandex#204]
При попытке изменения любого не последнего хоста в конфиге `yandex_mdb_postgresql_cluster` terraform пытается пересоздать все хосты. Ожидается поведение, когда при изменении отдельных хостов изменяются они и только они.

```
      ~ host {
          ~ subnet_id        = "e2l4u9j29cal2vo8i854" -> "b0cclpfber2u5dni60um"
          ~ zone             = "ru-central1-b" -> "ru-central1-c"
            # (4 unchanged attributes hidden)
        }
      - host {
          - assign_public_ip = false -> null
          - fqdn             = "rc1c-gnl9r2xuxqt262cg.mdb.yandexcloud.net" -> null
          - priority         = 0 -> null
          - role             = "REPLICA" -> null
          - subnet_id        = "b0cclpfber2u5dni60um" -> null
          - zone             = "ru-central1-c" -> null
        }
```

**Comment by k0t3n** [comment]
Related to #79

**Comment by apilikov** [comment]
Спасибо за это обращение. Мы сообщим вам как только проблема будет решена!

**Comment by apilikov** [comment]
Обсудили с командой и пришли к выводу что по факту изменений не производится, не смотря на то, что diff их отображает. Текущая ресурсная модель не позволяет это пофиксить просто, а элегантного решения, как это переделать, у нас сейчас нет. Возможно в будущем, если возникнет более серьезная проблема, мы это переделаем. Сожалеем что не удалось решить проблему полностью. Спасибо за обращение.

**Comment by k0t3n** [comment]
@apilikov у меня больше не воспроизводится на версии 0.68.0: изменяются только необходимые хосты, diff корректный. Есть возможность уточнить какая проблема не была решена?

**Comment by apilikov** [comment]
Не знаю что и сказать. Рад что проблемы больше нет. Будем считать что нерешенных проблем по данному кейсу у нас не осталось.
