### ISSUE TITLE
`yandex_compute_instance_group`: can't configure `auto_scale_type`

### ISSUE THREAD

**Issue by Nyoroon** [yandex-cloud/terraform-provider-yandex#214]
https://cloud.yandex.com/en/docs/compute/concepts/instance-groups/scale#auto-scale-type

**Comment by apilikov** [comment]
Thanks for reaching out! Did you try using https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/compute_instance_group#auto_scale ?

**Comment by Nyoroon** [comment]
Yes, it should be parameter of `auto_scale` block (currently not present).
API reference: https://github.com/yandex-cloud/cloudapi/blame/83dafd6b465cfa321dfd492f840ed480f7269493/yandex/cloud/compute/v1/instancegroup/instance_group.proto#L242-L250

**Comment by silaevdima** [comment]
Any news on this issue?

**Comment by glebarez** [comment]
same issue
