### ISSUE TITLE
Get backup_id from Data Sources (for restoring clusters MySQL from backup)

### ISSUE THREAD

**Issue by balagurrr** [yandex-cloud/terraform-provider-yandex#217]
Hi!
I really want  to get backup_id (for restoring clusters MySQL from backups) from Data Sources.

**Comment by apilikov** [comment]
Thank you very much for reaching out! You'll get notified once the issue is resolved.

**Comment by ostinru** [comment]
Hi @balagurrr , do you want to have actual list of backups that available for this cluster?
What is your workflow (what task are you solving)?
