### ISSUE TITLE
HttpRouterDeleteError for HttpRouter

### ISSUE THREAD

**Issue by balagurrr** [yandex-cloud/terraform-provider-yandex#229]
При удалении ресурса yandex_alb_http_router нужно чтобы сначала изменялся ресурс yandex_alb_load_balancer
иначе происходит ошибка:

HttpRouterDeleteError for HttpRouter: failed to delete http router that is referenced by a load balancer

**Comment by ascheglov** [comment]
Если у Вас написано 

```
resource "yandex_alb_load_balancer" "test-balancer" {
  listener {
    http {
      handler {
        http_router_id = yandex_alb_http_router.test-router.id
```
то перед удалением `test-router` надо изменить спеку test-balancer, например удалив listener.

Если Вы заменяте один роутер на другой, то используйте 

```
lifecycle {
    create_before_destroy = true  
}
```

(см. https://www.terraform.io/language/meta-arguments/lifecycle)
