### ISSUE TITLE
Add support a single record value longer than 255 characters such as a TXT record for DKIM

### ISSUE THREAD

**Issue by ilyash89** [yandex-cloud/terraform-provider-yandex#246]
Could you please add support for a single record value longer than 255 characters? 
For example: To specify a single record value longer than 255 characters such as a TXT record for DKIM, add \"\" inside the Terraform configuration string (e.g., "first255characters\"\"morecharacters").

**Comment by ilyash89** [comment]
Today I've got the following error when I tried to create DKIM record via Terraform: 
`Error: expected length of data.0 to be in the range (1 - 255)`

**Comment by vasiliy-briginets** [comment]
Thank you for the issue. Fixed by @mooncube - https://github.com/yandex-cloud/terraform-provider-yandex/pull/245
Will be released shortly
