### ISSUE TITLE
Get CNAME dns settings from yandex_cdn_resource attributes

### ISSUE THREAD

**Issue by bugchecker** [yandex-cloud/terraform-provider-yandex#252]
Cannot fetch CNAME url for Cloud CDN Resource like `cl-*.gcdn.co` from cli or terraform.
Docs: https://cloud.yandex.ru/docs/cdn/quickstart#setup-cname

**Comment by AlexeyBukin** [comment]
The CNAME you are talking about is actually is a **CDN provider's** CNAME.
That's very sad that for now you cannot create and manage CDN provider via Terraform. I hope Yandex Cloud team consider creating this resource type in the future.

For now I use the "hack":
```terraform
data "external" "cdn_provider_cname" {
  program = ["yc", "--impersonate-service-account-id=${var.service_account_id}", "cdn", "resource", "get-provider-cname", "--no-user-output", "--format=json"]
}
```
You are required to have access to service account `service_account_id` or use it without flag `--impersonate-service-account-id` and have access to requesting folder with current `yc` profile.

Example recordset using this data:
```terraform

resource "yandex_dns_recordset" "cdn_website" {
  zone_id = yandex_dns_zone.public_dns_zone.id
  name    = "www.${var.domain_base}."
  type    = "ANAME"
  ttl     = 60
  data    = [data.external.cdn_provider_cname.result.cname] # here is the trick
}
```

**Comment by AlexeyBukin** [comment]
@seukyaso What do you think? Is there a better solution?

**Comment by opportunity356** [comment]
Issue is actual.

**Comment by max-arnold** [comment]
It is implemented: https://github.com/yandex-cloud/terraform-provider-yandex/commit/b496f7a29c28936b21441cffdc8f65fdc66223d9

**Comment by bugchecker** [comment]
@AlexeyBukin I found a temporary solution in hardcoding the domain. It is the same for all my distribution in fact.

**Comment by max-arnold** [comment]
The `yandex_cdn_resource.mycdn.provider_cname` attribute works for me

**Comment by govyadkin** [comment]
> @AlexeyBukin I found a temporary solution in hardcoding the domain. It is the same for all my distribution in fact.

Tell me which version of the provider do you use?

**Comment by opportunity356** [comment]
> Tell me which version of the provider do you use?

https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.117.0
