### ISSUE TITLE
https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs is not available from Russia

### ISSUE THREAD

**Issue by FractalizeR** [yandex-cloud/terraform-provider-yandex#258]
Terraform seem to be blocking Russian IPs. Documentation needs to be moved away ;)

**Comment by kuzaxak** [comment]
You can check mirror [here][1]

[1]: https://registry.tfpla.net/providers/yandex-cloud/yandex/latest/docs

**Comment by FractalizeR** [comment]
Yeah, thanks. Got it from support already. I mean that documentation in your README, which is displayed at the repo root (https://github.com/yandex-cloud/terraform-provider-yandex) needs to be updated

**Comment by panovmikhail** [comment]
hello, faced the same issue. Any updates?

**Comment by FractalizeR** [comment]
@kuzaxak https://registry.tfpla.net/providers/yandex-cloud/yandex/latest/docs is dead (NXDOMAIN). Can you please update the docs pointing to ANY existing documentation for the provider?

**Comment by FractalizeR** [comment]
https://docs.comcloud.xyz/providers/yandex-cloud/yandex/latest/docs

This mirror is still alive. Why don't Yandex host one if we are blocked from official one?

**Comment by FractalizeR** [comment]
Any updates? Official documentation still references registry.terraform.io, which has Russia blocked away.

**Comment by FractalizeR** [comment]
Up. Official link at this repo still points to the content, unavailable from Russia.

**Comment by govyadkin** [comment]
Actually doc https://terraform-provider.yandexcloud.net/

**Comment by FractalizeR** [comment]
> Actually doc https://terraform-provider.yandexcloud.net/

![image](https://github.com/user-attachments/assets/b01b462d-216f-4644-b207-450e3407df1a)

@govyadkin 
Not on the main repo page
