### ISSUE TITLE
Error on importing yandex_storage_bucket resource

### ISSUE THREAD

**Issue by asterix201** [yandex-cloud/terraform-provider-yandex#27]
Hello, 

How to import a previously created storage bucket? 

I've added resource into my tf plan: 
```
resource "yandex_storage_bucket" "old_bucket" {
  bucket = "bucket.name"
  access_key = "access_key"
  secret_key = "secret_key"
}
```

But when I'm trying to do an import, I'm getting an error: 

```
terraform import yandex_storage_bucket.old_bucket bucket.name 
yandex_storage_bucket.old_bucket: Importing from ID "bucket.name"...
yandex_storage_bucket.old_bucket: Import prepared!
  Prepared yandex_storage_bucket for import
yandex_storage_bucket.old_bucket: Refreshing state... [id=bucket.name]

Error: error getting storage client: failed to get default storage client
```

**Comment by alexanderKhaustov** [comment]
To import a bucket you should specify access and secret keys in the provider configuration (storage_access_key and storage_secret_key). This managed to escape the provider config documentation, we'll update it shortly.

**Comment by GennadySpb** [comment]
@asterix201 Hi! 
Did you manage the import operation?

**Comment by asterix201** [comment]
@GennadySpb , hello! 

Sorry for the delay. 
Yes, after I've added storage_access_key and storage_secret_key into provider configuration I could import previously created bucket. 

Do I need to set these variables to create and manage new buckets from terraform? 

@alexanderKhaustov
Thanks for your help!

**Comment by GennadySpb** [comment]
@asterix201 so to create and manage buckets you could set credentials either on provider config level or resource definition.

**Comment by asterix201** [comment]
Sorry for the delay. 
Now it works fine, thank you!

**Comment by bryzgaloff** [comment]
@alexanderKhaustov 

> To import a bucket you should specify access and secret keys in the provider configuration (storage_access_key and storage_secret_key).

Which minimal permissions does this service account need to have? I have granted `editor` permissions and I am wondering isn't it too broad.
