### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by pelid** [yandex-cloud/terraform-provider-yandex#291]
Terraform отказывается обновлять провайдер yandex:

```shell-session
$ terraform init -upgrade
...
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider terraform-registry.storage.yandexcloud.net/yandex-cloud/yandex: no available releases match the
│ given constraints >= 0.70.0, 0.73.0
```

Проблемы возникают с версиями с 0.73.0 по 0.78.0 включительно. При этом вполне удаётся обновиться с 0.71.0 до 0.72.0.

Попытался решить проблему обновление Terraform до последней версии v1.2.8 — не помогло.

**Comment by pelid** [comment]
В итоге решил проблему с помощью зеркала. Скачал свежую версию провайдера с registry.tfpla.net:

```tf
terraform {
  required_providers {
    yandex = {
      # source = "terraform-registry.storage.yandexcloud.net/yandex-cloud/yandex"  # старый вариант
      source = "registry.tfpla.net/yandex-cloud/yandex"
      version = "0.84.0"
    }
}

**Comment by pelid** [comment]
UPD. Альтенативный способ указан в документации. [Яндекс Облако — Настройте провайдер](https://cloud.yandex.ru/docs/tutorials/infrastructure-management/terraform-quickstart#configure-provider). Тоже работает.

**Comment by Denriful** [comment]
Теперь оба варианта не работают.
