### ISSUE TITLE
Resource yandex_compute_snapshot_schedule trigger disk reattachment and failed during apply

### ISSUE THREAD

**Issue by VictorEfim** [yandex-cloud/terraform-provider-yandex#309]
Hello,

We used the new resource **yandex_compute_snapshot_schedule** to create snapshot schedule and it created successfully, but next terraform plans trigger the existing disks reattachment:

```
 yandex_compute_snapshot_schedule.example-schedule will be updated in-place
 resource "yandex_compute_snapshot_schedule" "example-schedule" {
      ~ disk_ids       = [
          - "epd177vk9652tir50bpb",
            "epd68n4vdp85hjfsvlo4",
          + "epd177vk9652tir50bpb",
        ]
        id             = "fd8m2hoo0hh8m2puv658"
        name           = "example-schedule"
        # (5 unchanged attributes hidden)
        # (2 unchanged blocks hidden)
    }
```
 and then terraform apply failed with error:

`Error: Error updating SnapshotScheduleDisks: Error while requesting API to update SnapshotSchedule disks "fd8p9cm5v0hihjf3qdqn": server-request-id = 3cbacbe9-0aeb-4de2-9f62-e9d1096b8e33 server-trace-id = 1ac4bb47cca5684c:4754e8fe631b5bc3:1ac4bb47cca5684c:1 client-request-id = a5fab3a4-a8b0-49b6-b5c4-fb9601b5d63d client-trace-id = 71acc2f9-c8d9-4a2e-a340-50d1ec1920e0 rpc error: code = InvalidArgument desc = Request validation error: Snapshot schedule "fd8p9cm5v0hihjf3qdqn" already contains disks...`

Also it's unclear how to use **retention_period** argument in this resource, because it's failed both in choosing the just number and the time in hour/day with error:

`Error: time: missing unit in duration "21"`

**Comment by KoDA82** [comment]
Fixed at https://github.com/yandex-cloud/terraform-provider-yandex/commit/6b618e19e4226c38e50d17fb650dbb0df3c04ece
