### ISSUE TITLE
Possibility to create folders

### ISSUE THREAD

**Issue by webchi** [yandex-cloud/terraform-provider-yandex#31]
I think creating folders should be able from provider resource

**Comment by GennadySpb** [comment]
Hi @webchi ! Thanks for feature request!

Full support of this kind of resource requite availability of delete method in public API. [Right now](https://cloud.yandex.com/docs/resource-manager/api-ref/Folder/delete) it temporary lacks.

**Comment by apilikov** [comment]
The issue has been resolved recently. Feel free to reopen if the problem is still there. Thank you!
