### ISSUE TITLE
metadata_options

### ISSUE THREAD

**Issue by dushasokol-tasks** [yandex-cloud/terraform-provider-yandex#318]
Hi there!

In the manifest I declare:

resourse "yandex_compute_instance" "test" {
```
...
            metadata_options = {
                aws_v1_http_endpoint: 0,
                aws_v1_http_token: 0,
                gce_http_endpoint: 0,
                gce_http_token: 0
            }
...
```

I expect that there will be no access to '169.254.169.254' from within the VM.

In fact, access remains. Checking the status:

`terraform state show yandex_compute_instance.test`
```
...

            "metadata_options": [
              {
                "aws_v1_http_endpoint": 1,
                "aws_v1_http_token": 1,
                "gce_http_endpoint": 1,
                "gce_http_token": 1
              }
            ],
...
```

If you do apply again, it prints that terraform needs to patch infra:
`~"aws_v1_http_endpoint": 1 -> 0 ...`

After apply it prints that OK, `1 changed`, but there is no effect and meta-URL is open on the machines.
If you look the state again, all the values are still in `1`.

In the working directory in `.terraform` folder providers are `0.84.0` and `0.74.0`, there are no special settings for the preferred provider version.

**Comment by ITD27M01** [comment]
Hi, looks like it is because of this: https://cloud.yandex.ru/blog/posts/2023/02/disable-aws-token
