### ISSUE TITLE
Public static IP

### ISSUE THREAD

**Issue by d-i-bondarenko** [yandex-cloud/terraform-provider-yandex#33]
There is no way to create public static IP via Terraform (or create VM with static IP option). It would be great to have this feature and add more code control to cloud infrastructure.

**Comment by GennadySpb** [comment]
Hi @d-i-bondarenko ! Thanks for requesting feature! 

This is a very demanded feature. Right now there is a dependency on its presence in the Yandex.Cloud public API.

**Comment by baffolobill** [comment]
It seems this feature appeared in CLI `yc compute instance create` via `--public-address` or `--network-interface nat-address=...`.

@GennadySpb Does that mean we will see this feature in Terraform soon?

**Comment by GennadySpb** [comment]
@baffolobill 
We are on the way to implementing full support for managing NAT addresses. One of the steps taken is the ability to assign a previously reserved address to the instance.

Take a look at [nat_ip_address](https://www.terraform.io/docs/providers/yandex/r/compute_instance.html#nat_ip_address).

**Comment by nivolk** [comment]
Hey!
When will it be possible to use a static IP address in virtual machines?

**Comment by damirm** [comment]
@gitkv @d-i-bondarenko @baffolobill

Hey! You can manage static ip addresses via `yandex_vpc_address` resource https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/vpc_address

Also you can attach static ip address by address value to instance via `nat_ip_addess` https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/compute_instance#nat_ip_address

Example: 
```
resource "yandex_vpc_address" "test-address" {
  name = "test-addr"
  external_ipv4_address {
    zone_id = "ru-central1-a"
  }
}

resource "yandex_compute_instance" "default" {
  name        = "test"
  platform_id = "standard-v1"
  zone        = "ru-central1-a"

  resources {
    cores  = 2
    memory = 4
  }

  boot_disk {
    initialize_params {
      image_id = "image_id"
    }
  }

  network_interface {
    subnet_id = "subnet_id"
    nat = true
    nat_ip_address = yandex_vpc_address.test-address.external_ipv4_address[0].address
  }
}
```

**Comment by Wolfeg** [comment]
@damirm i'm trying to create public ip via [this doc](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/vpc_address#address) with this block
```
resource "yandex_vpc_address" "dev" {
  name = "vpn-dev"
  external_ipv4_address {
    address = var.static_nat_ip
  }
}
```
but getting error `Error: "external_ipv4_address.0.address": this field cannot be set`
Is this feature still not implemented yet?

**Comment by damirm** [comment]
@Wolfeg 
> but getting error `Error: "external_ipv4_address.0.address": this field cannot be set`
> Is this feature still not implemented yet?

Currently you can't specify desired address, it's an error in documentation.

**Comment by apilikov** [comment]
Closing the issue, documentation update is on the way.

**Comment by Jasstkn** [comment]
> Closing the issue, documentation update is on the way.

Hi. I see that the documentation wasn't updated. And I ran into this issue because of it.
```
Can't configure a value for "external_ipv4_address.0.address": its value will be decided automatically based on the result of applying this configuration.
```

At the same time I was able to import the resource into terraform.
