### ISSUE TITLE
How to use instance.index or instance.short_id in yandex_kubernetes_node_group -> instance_template -> name

### ISSUE THREAD

**Issue by edmiachkov** [yandex-cloud/terraform-provider-yandex#333]
Hello, guys. In Terraform doc for [yandex_kubernetes_node_group](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/kubernetes_node_group#fixed_scale) you may see:

The **instance_template** block supports:
<...>
- [name](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/kubernetes_node_group#name) - (Optional) Name template of the instance. In order to be unique it must contain at least one of instance unique placeholders:
{instance.short_id}
{instance.index}
combination of {instance.zone_id} and {instance.index_in_zone}
Example: my-instance-{instance.index}
If not set, default is used: {instance_group.id}-{instance.short_id}
It may also contain another placeholders, see [Compute Instance group metadata doc](https://cloud.yandex.com/en-ru/docs/compute/api-ref/grpc/instance_group_service) for full list.

But I cannot understand how to use **instance.index** or **instance.short_id** or whatever **instance.*** here. 

I am trying to have understandable Node VM name, and I get the error like:
`- name: Field must contain proper placeholder combination in order to guarantee uniqueness`

And if I use **instance.index** or **instance.short_id** in the name attribute I see this error:
```
│ Error: Reference to undeclared resource
│ 
│   on kubernetes.tf line 61, in resource "yandex_kubernetes_node_group" "node-group-dev-a":
│   61:     name = "${yandex_kubernetes_cluster.k8s-dev.name}-node-${instance.index}"
│ 
│ A managed resource "instance" "index" has not been declared in the root
│ module.
```

**Comment by edmiachkov** [comment]
I figured out how. Need to use quotes and don't use $ sign.

Like  `name = "node-{instance.short_id}"`

I hope that will help to someone who is stuck with poor documentation like me.

**Comment by Real-Gecko** [comment]
> I figured out how. Need to use quotes and don't use $ sign.
> 
> Like `name = "node-{instance.short_id}"`
> 
> I hope that will help to someone who is stuck with poor documentation like me.

Thanks, saved my day. Would be nice for it to be reflected in docs as example.
