### ISSUE TITLE
feature request: opensearch 

### ISSUE THREAD

**Issue by mrPsycho** [yandex-cloud/terraform-provider-yandex#355]
Hello, 

as i received message, that elastic won't be here anymore, so we need support of opensearch.

**Comment by mrPsycho** [comment]
so sad, that nowadays there is no way use nothing of it, and need to come back to self installed tools

**Comment by ssch1337** [comment]
@GennadySpb @apilikov
Привет, планируются ли работы по этому фича реквесту? Если в ближайшее время нет, то я готов сделать PR.

**Comment by Cockamamie** [comment]
Привет, ну я вообще просто студент, который одну маленькую функциональность завез. Не знаю, как ты меня сюда приплел)

**Comment by ssch1337** [comment]
Извини, видимо в твоём PR перепутал тебя с ревьювером

**Comment by mrPsycho** [comment]
first version, i guess: https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.103.0

**Comment by opportunity356** [comment]
@mrPsycho, hi, you are right. Since 0.103.0 provider is supporting opensearch. Is your issue solved and can be closed?
