### ISSUE TITLE
postgresql resource

### ISSUE THREAD

**Issue by juwit** [yandex-cloud/terraform-provider-yandex#36]
Hi there :wave: 

It would be nice if we could create postgresql clusters with a terraform resource.

**Comment by GennadySpb** [comment]
Hi! 
Work on the postgresql cluster resource is already in progress. Stay tuned ;)

**Comment by GennadySpb** [comment]
Check the [0.29.0](https://github.com/terraform-providers/terraform-provider-yandex/blob/master/CHANGELOG.md#0290-january-24-2020) release out! 
Support of PostgreSQL & MySQL clusters arrived.

**Comment by juwit** [comment]
Great news ! I believe we can close this issue ! Thanks !
