### ISSUE TITLE
Can't created PostgreSQL MDB cluster with disk type network-ssd-nonreplicated

### ISSUE THREAD

**Issue by akvakh** [yandex-cloud/terraform-provider-yandex#362]
Yandex cloud provider accepts disk size in gigabytes, but the API itself accepts parameter in bytes can handle only specific numbers in disk_size parameter if non-replicated disk is used. This results in the following error

│ Error: Error while requesting API to create PostgreSQL Cluster: server-request-id = 8df017a6-909f-4498-b790-9726ad93c44e server-trace-id = efb83964f8ceb780:8772a3b7e7cd2d1a:efb83964f8ceb780:1 client-request-id = fadaa8b5-a2aa-4d8e-b05c-fb8a3bede5c3 client-trace-id = 83350937-87fe-4a43-9a10-61c1d08c8456 rpc error: code = FailedPrecondition desc = Invalid disk_size, use one of [99857989632, 199715979264, 299573968896, 399431958528, 499289948160, 599147937792, 699005927424, 798863917056, 898721906688, 998579896320, 1098437885952, 1198295875584, 1298153865216, 1398011854848, 1497869844480, 1597727834112, 1697585823744, 1797443813376, 1897301803008, 1997159792640, 2097017782272, 2196875771904, 2296733761536, 2396591751168, 2496449740800, 2596307730432, 2696165720064, 2796023709696, 2895881699328, 2995739688960, 3095597678592, 3195455668224, 3295313657856, 3395171647488, 3495029637120, 3594887626752, 3694745616384, 3794603606016, 3894461595648, 3994319585280, 4094177574912, 4194035564544, 4293893554176, 4393751543808, 4493609533440, 4593467523072, 4693325512704, 4793183502336, 4893041491968, 4992899481600, 5092757471232, 5192615460864, 5292473450496, 5392331440128, 5492189429760, 5592047419392, 5691905409024, 5791763398656, 5891621388288, 5991479377920, 6091337367552, 6191195357184, 6291053346816, 6390911336448, 6490769326080, 6590627315712, 6690485305344, 6790343294976, 6890201284608, 6990059274240, 7089917263872, 7189775253504, 7289633243136, 7389491232768, 7489349222400, 7589207212032, 7689065201664, 7788923191296, 7888781180928, 7988639170560, 8088497160192, 8188355149824, 8288213139456, 8388071129088, 8487929118720, 8587787108352, 8687645097984, 8787503087616, 8887361077248, 8987219066880, 9087077056512, 9186935046144, 9286793035776, 9386651025408, 9486509015040, 9586367004672, 9686224994304, 9786082983936, 9885940973568, 9985798963200, 10085656952832, 10185514942464, 10285372932096, 10385230921728, 10485088911360, 10584946900992, 10684804890624, 10784662880256, 10884520869888, 10984378859520]

**Comment by kvmukhin** [comment]
Size non-replication disk MUST be multiple 93Gb. Example 93, 186, 279...

**Comment by akvakh** [comment]
@kvmukhin thanks a lot!
