### ISSUE TITLE
yandex_cdn_resource, certificate management not documented

### ISSUE THREAD

**Issue by baznikin** [yandex-cloud/terraform-provider-yandex#366]
With web console you can set Certificate type
![image](https://github.com/yandex-cloud/terraform-provider-yandex/assets/5183334/f468fd74-3083-4a58-a60b-144d0b7e8fc8)
However, documentation mention only some `ssl_certificate` completely undocumented option. Only after reading source code I figure out how to use it:
```
resource "yandex_cdn_resource" "test" {
  cname = "cdn-kb.example.com"
  ssl_certificate {
    type = "lets_encrypt_gcore"
  }
}
```
Also it is issue similar to #365 - removing `ssl_certificate{}` block from resource definition do not reset certificate type to default type `not_used`

**Comment by opportunity356** [comment]
Hi! This option is no longer supported
