### ISSUE TITLE
yandex_vpc_subnet.name not validated properly at plan stage

### ISSUE THREAD

**Issue by ivonin** [yandex-cloud/terraform-provider-yandex#38]
`yandex_vpc_subnet.name` attribute doesn't allow upper-case letters.

When trying to create a subnet with a name `production-VM-ru-central1-a`, 
`terraform plan` doesn't raise any errors, but `terraform apply` fails:

> Error: Error while requesting API to create subnet: server-request-id = .... client-request-id = .... client-trace-id = .... 
> rpc error: code = InvalidArgument desc = name: Invalid resource name 

It would be really nice to see these errors at plan stage.

**Comment by GennadySpb** [comment]
Hi @ivonin !
The lack of validation at the terraform provider level is clearly a given behavior. Perhaps in the future such a strict restriction of the network name may be removed.

**Comment by ivonin** [comment]
> The lack of validation at the terraform provider level is clearly a given behavior.

What do you mean by "given behavior"? Is it something that's by design? If so, can you clarify why?

**Comment by GennadySpb** [comment]
Yeah, it's by design. If in the future the strictness on names is weakened, then validation on the client will prevent the use of new naming capabilities.

**Comment by ivonin** [comment]
Yeah.. Can't say I completely agree with this approach. Seems like this kind of future-proofing is neither useful (as it limits the amount of validation) nor necessary (considering that terraform plugins support versioning and forward compatibility is not needed).

Still, thanks for your explanation, I'll be closing the issue now.
