### ISSUE TITLE
yandex_compute_instance - невозможность прокинуть через metadata ключ для пользователя, отличного от ubuntu

### ISSUE THREAD

**Issue by AnvilFox1965** [yandex-cloud/terraform-provider-yandex#382]
Добрый день!

При передаче в ресурс `yandex_compute_instance` блока metadata в подобном виде:
```
  metadata = {
    ssh-keys = "${var.instances_user_name}:${var.ssh_public_key}"
  }
```
и, соответственно, указанием в `variables.tf` пользователя, отличного от `ubuntu`:
```
variable "instances_user_name" {
  default = "non-ubuntu-user"
}
```
новый пользователь не создается, хотя в веб-интерфейсе облака информация в метаданных отображается верно.
Похоже на баг, тк при создании пользователя из того же веб-интерфейса указание кастомного пользователя работает.

Посмотрите, пожалуйста.

**Comment by ka1bi4** [comment]
Тут скорее особенность работы с публичными образами: https://cloud.yandex.ru/docs/compute/concepts/vm-metadata#how-to-send-metadata

Лучше использовать конструкцию:
```
metadata = {
  user-data = "#cloud-config\nusers:\n  - name: <имя_пользователя>\n    groups: sudo\n    shell: /bin/bash\n    sudo: 'ALL=(ALL) NOPASSWD:ALL'\n    ssh-authorized-keys:\n      - <содержимое_SSH-ключа>"
}
```
подставив свои var

**Comment by AnvilFox1965** [comment]
Т.е. явно дать понять `cloud-init`'у создать нового пользователя.
Благодарю за оперативность! Протестирую.
