### ISSUE TITLE
bug yandex-cloud/yandex v0.100.0

### ISSUE THREAD

**Issue by Lakhonin** [yandex-cloud/terraform-provider-yandex#385]
I've make terraform plan (yandex-cloud/yandex v0.100.0, Terraform v1.0.11) and get an error 

_Provider "registry.terraform.io/yandex-cloud/yandex" planned an invalid
│ value for yandex_resourcemanager_folder.folder.labels: planned value
│ cty.MapValEmpty(cty.String) for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker._

Resource yandex_resourcemanager_folder does not have any label specified

``resource "yandex_resourcemanager_folder" "folder" {``
 `` cloud_id    = "${var.cloud_id}"``
 `` name        = "retail"``
 `` description = "sale of goods and services"
}``

By the way: on the yandex-cloud/yandex v0.99.0 all works fine
What changed in version v0.99.0 -> v0.100.0?

**Comment by tariver** [comment]
I second this, got the same error with terraform version 1.0.11

```HCL
Error: Provider produced invalid plan

Provider "registry.terraform.io/yandex-cloud/yandex" planned an invalid value for yandex_vpc_gateway.dev.description: planned value cty.StringVal("") for a non-computed attribute.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

yandex-cloud/yandex v0.99.0 works fine also.

**Comment by countneuroman** [comment]
Got the same error with provider version 0.102.0

**Comment by countneuroman** [comment]
I originally used version = ">= 0.87.0" and I was getting the same errors. If I change to version = ">= 0.92.0", the error disappears. In both cases, 0.102.0 is set as the latest current version.

**Comment by KoDA82** [comment]
Hi, sorry for the delay in processing.
Is this issue still relevant?
