### ISSUE TITLE
add info about opentofu

### ISSUE THREAD

**Issue by mrPsycho** [yandex-cloud/terraform-provider-yandex#397]
As terraform changed license type - maybe it is a good thing to switch to https://opentofu.org/.

**Comment by KoDA82** [comment]
We're thinking about it, but would like to wait for the stable version.

**Comment by soundcarrot** [comment]
> JANUARY 10, 2024
> OpenTofu is going GA

https://opentofu.org/blog/opentofu-is-going-ga/

**Comment by kvendingoldo** [comment]
@KoDA82 any news?

**Comment by KoDA82** [comment]
Not yet. Still watching if latest stable release is really stable :)

**Comment by unixzen** [comment]
Hello! Any news? Looks so bad news https://www.hashicorp.com/blog/hashicorp-joins-ibm. And OpenTofu stable release 1.7.0.

**Comment by KoDA82** [comment]
We decided not to switch to OpenTofu within next year (of course if we'll not face any issues with Hashicorp).
