### ISSUE TITLE
Is this repository already deprecated?

### ISSUE THREAD

**Issue by kchugalinskiy** [yandex-cloud/terraform-provider-yandex#4]
Occasionally we've noticed the same repository here: https://github.com/terraform-providers/terraform-provider-yandex
Does this mean that this repository is already outdated and the new one should be used for contributions? In this case could you please mark this one as either deprecated or moved to the new place?

**Comment by GennadySpb** [comment]
Hello! Thanks for for comment.

Yes, after few code review cycles code was moved to [new official location](https://github.com/terraform-providers/terraform-provider-yandex). Please use new repo for contributions.

**Comment by GennadySpb** [comment]
Notice about repository deprecation was added.
