### ISSUE TITLE
yc backend storage

### ISSUE THREAD

**Issue by kchugalinskiy** [yandex-cloud/terraform-provider-yandex#4]
Hello,

 I propose to implement new yc backend storage and contribute it into https://github.com/hashicorp/terraform/tree/master/backend/remote-state as I suppose all hacks around s3 backend unacceptable for such company as Yandex. Let's discuss how community can be helpful and if someone from inside your team has either some ideas or workarounds how to implement this storage.

State storage is extremely helpful in case of team collaboration development and I'm not sure that it is OK to use some hacks like minio for this functional.

**Comment by GennadySpb** [comment]
Hello,

This is good proposal. To implement such a storage, it is necessary to fulfill a number of requirements.
Among them is the extension of the API of Yandex Object Storage.
As soon as this happens, it will be possible to implement new "yc" backend storage.

**Comment by apilikov** [comment]
Closing the issue as there is no updates for a long time.
