### ISSUE TITLE
неправильные ссылки в документации

### ISSUE THREAD

**Issue by vladimir4862** [yandex-cloud/terraform-provider-yandex#401]
Не уверен где это надо поправлять тут, или где то ещё где она выгружается на сайт https://terraform-provider.yandexcloud.net
но переход по ссылкам внизу страниц приводит к ошибкам вида 
<img width="597" alt="Снимок экрана 2023-11-30 в 09 19 35" src="https://github.com/yandex-cloud/terraform-provider-yandex/assets/15683877/36979e3d-3269-4f5d-9622-d63a4ced464b">

**Comment by KoDA82** [comment]
Привет!
Можно и сюда про такое отписываться. Проблему забрали - закроем Issue, как починим.

**Comment by KoDA82** [comment]
Исправили.
