### ISSUE TITLE
Refreshing state для единственного s3 bucket занимает более 1 минуты

### ISSUE THREAD

**Issue by max107** [yandex-cloud/terraform-provider-yandex#421]
Минимально воспроизводимый пример. Наблюдается константно, вне зависимости от сети / локации / бакита.

```
locals {
  bucket = "foobar-example"
}

resource "yandex_iam_service_account" "root-sa" {
  name = "proto"
}

resource "yandex_resourcemanager_folder_iam_member" "root-sa" {
  folder_id = local.folder_id
  role      = "storage.editor"
  member    = "serviceAccount:${yandex_iam_service_account.root-sa.id}"
}

resource "yandex_iam_service_account_static_access_key" "static-key" {
  service_account_id = yandex_iam_service_account.root-sa.id
}

resource "yandex_storage_bucket" "proto" {
  access_key = yandex_iam_service_account_static_access_key.static-key.access_key
  secret_key = yandex_iam_service_account_static_access_key.static-key.secret_key
  bucket     = local.bucket
```

**Comment by somewho** [comment]
вроде в свежих версиях не актуально

**Comment by max107** [comment]
@somewho уточните пожалуйста начиная с какой версии?

**Comment by somewho** [comment]
> @somewho уточните пожалуйста начиная с какой версии?

на данный момент использую 0.124.0, прописан один бакет, проблем с торможением на обновлении статуса не наблюдаю, проект на пару десятков разнообразных ресурсов:
terraform plan  1.10s user 0.26s system 28% cpu 4.721 total

**Comment by MikailBag** [comment]
Я тоже столкнулся с этой проблемой и в #437 описал свои наблюдения.

TL&DR: если операции с s3 выполняются от имени СА, у которого нет роли storage.admin, то провайдер не может считать bucket policy бакета, и ретраит это в течение одной минуты.

Я также принес связанный ПР #444, который был смержен как раз в версии 0.124.0. Но если он поправил эту проблему, то для меня это неожиданность :)

**Comment by Fluffi1235** [comment]
@MikailBag удалось ли проверить, что данная проблема решена ?

> Я также принес связанный ПР #444, который был смержен как раз в версии 0.124.0. Но если он поправил эту проблему, то для меня это неожиданность :)

**Comment by MikailBag** [comment]
Я думаю, тут уже нужно разбираться коллегам из Yandex Cloud. Я подробных тестов не проводил.
