### ISSUE TITLE
How to get created data nodes list?

### ISSUE THREAD

**Issue by kbalyasnikov** [yandex-cloud/terraform-provider-yandex#426]
This information is required for further cluster connection string building.

**Comment by opportunity356** [comment]
@kbalyasnikov Hi! Could you please provide extra details on your question. Snippet of resource code would be helpful

**Comment by kbalyasnikov** [comment]
With Elasticsearch module I could do this:

```
output "hosts" {
  value = [for host in yandex_mdb_elasticsearch_cluster.cluster.host[*].fqdn : "${host}:9200"]
}
```

I can't do the same with Opensearch module.

**Comment by opportunity356** [comment]
@kbalyasnikov, thanks for response. Unfortunately, this functionality is not supported yet. Added a task to the team's backlog. Please don't close the issue. Further updates will be provided here

**Comment by opportunity356** [comment]
@kbalyasnikov hi! Computed `hosts` attribute for yandex_mdb_opensearch_cluster was added in https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.117.0. Should work the same way as for elasticsearch. Please give it a try
