### ISSUE TITLE
Как с помощью terraform установить роль на S3 bucket ?

### ISSUE THREAD

**Issue by LuckySB** [yandex-cloud/terraform-provider-yandex#429]
В [документации на облако](https://yandex.cloud/ru/docs/storage/operations/buckets/iam-access) есть возможность установить сервисному аккаунту права доступа на конкретный S3 бакет.
Через назначение роли.

А возможно ли осуществить такую операцию с помощью terraform провайдера yandex ?

**Comment by PeppaTheC** [comment]
Привет, воспользуйся ресурсом `yandex_resourcemanager_folder_iam_member `. Как показано в [документации](https://terraform-provider.yandexcloud.net/Resources/storage_bucket.html#example-usage)

**Comment by LuckySB** [comment]
мда. @PeppaTheC ресурс `yandex_resourcemanager_folder_iam_member` устанавливает права на весь folder (каталог в терминологии яндекс облака).
В итоге в документации пример который создает сервис аккаунт и выдает ему роль storage.editor, для того, чтобы далее терраформ смог создать бакет.
Ну и соотвественно у этого сервис аккаунта есть доступы ко всем бакетам, которые находятся в этом облачном каталоге.

А мне надо дать доступ к уже существующему бакету. только к Одному!!!

**Comment by somewho** [comment]
@PeppaTheC переоткройте исью, и так с вашей реализацией s3 через терраформ куча проблем, а тут еще и вопрос безопасности

**Comment by PeppaTheC** [comment]
> мда. @PeppaTheC ресурс `yandex_resourcemanager_folder_iam_member` устанавливает права на весь folder (каталог в терминологии яндекс облака). В итоге в документации пример который создает сервис аккаунт и выдает ему роль storage.editor, для того, чтобы далее терраформ смог создать бакет. Ну и соотвественно у этого сервис аккаунта есть доступы ко всем бакетам, которые находятся в этом облачном каталоге.
> 
> А мне надо дать доступ к уже существующему бакету. только к Одному!!!

Если нужно управлять правами отдельного бакета, воспользуйтесь `bucket policy`. 
https://yandex.cloud/ru/docs/storage/operations/buckets/policy#apply-policy

**Comment by somewho** [comment]
> мда. @PeppaTheC ресурс `yandex_resourcemanager_folder_iam_member` устанавливает права на весь folder (каталог в терминологии яндекс облака). В итоге в документации пример который создает сервис аккаунт и выдает ему роль storage.editor, для того, чтобы далее терраформ смог создать бакет. Ну и соотвественно у этого сервис аккаунта есть доступы ко всем бакетам, которые находятся в этом облачном каталоге.
> 
> А мне надо дать доступ к уже существующему бакету. только к Одному!!!

оставлю тут пример установки прав через policy на всякий случай

```hcl
resource "yandex_iam_service_account" "storage-sa" {
  name        = "storage-sa"
}

resource "yandex_resourcemanager_folder_iam_member" "storage-viewer" {
  folder_id = var.folder_id
  member    = "serviceAccount:${yandex_iam_service_account.storage-sa.id}"
  role      = "storage.configViewer"
}

resource "yandex_storage_bucket" "my-bucket" {
  access_key = var.object_storage_api_key
  secret_key = var.object_storage_api_secret
  bucket     = "my-storage"

  max_size = 10737418240

  grant {
    permissions = ["READ", "WRITE"]
    type        = "CanonicalUser"
    id          = yandex_iam_service_account.storage-sa.id
  }
}
```
