### ISSUE TITLE
Добавить получение FQDN DATA-ноды кластера OpenSearch

### ISSUE THREAD

**Issue by cheshirbis** [yandex-cloud/terraform-provider-yandex#433]
Текущая реализация OpenSearch в ЯО не позволяет прямым способом получить доменное имя FQDN DATA-ноды кластера. Для реализации этого функционала мне пришлось написать скрипт, который через API Яндекс Облака вытаскивает нужное значение (https://yandex.cloud/ru/docs/managed-opensearch/api-ref/Cluster/listHosts)

Прошу добавить возможность получения этого параметра через встроенные в resource механизмы (как, например, реализовано получение FQDN DASHBOARDS-ноды).

**Comment by MrChaos1993** [comment]
Добрый день @cheshirbis!
Начиная с версии [0.117.0](https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.117.0) было добавлено поле `hosts` содержащее список хостов кластера. В данном списке содержатся объекты, в которых есть поле `fqdn` соответствующее хостам. Так же вы можете использовать поля `type` и `roles` для фильтрации хостов по типу и ролям. 

Если данный функционал полностью удовлетворяет вашим потребностям, то прошу закрыть эту задачу. 
Заранее спасибо!

**Comment by cheshirbis** [comment]
А инструкцию для ЯО вы пишите? Может быть стоит там это явно описать? 
На момент моей работы с этим ресурсом, там точно не было информации. Точнее даже была, но предполагала запрос имени НЕ-DASHBOARDS ноды только через API.

**Comment by MrChaos1993** [comment]
Не до конца понимаю какую инструкцию вы имеете ввиду, можете уточнить?
В инструкции к ресурсу в терраформе описание поля `hosts` [присутствует](https://terraform-provider.yandexcloud.net/Resources/mdb_opensearch_cluster.html#attributes-reference)

**Comment by cheshirbis** [comment]
Я использовал инструкцию https://yandex.cloud/ru/docs/managed-opensearch/
К сожалению, это было уже почти полгода назад и я не помню подробностей. Но чтобы мне получить имя ноды пришлось делать вот так дополнительным скриптом (который выполнялся как local-exec в манифесте terraform):
```
result=$(curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $token" "https://mdb.api.cloud.yandex.net/managed-opensearch/v1/clusters/$CLUSTER_ID/hosts" | jq -r '.hosts[]? | select(.roles // [] | contains(["DATA"])) | .name')
output=$(jq --null-input --arg fqdn "$result" '{"fqdn": $fqdn}')
```
(это только смысловая часть скрипта)

**Comment by MrChaos1993** [comment]
Да, к сожалению до релиза 0.117.0 не было возможности получить список хостов в terraform.
Теперь вы можете обращаться к полю `hosts` у ресурса `yandex_mdb_opensearch_cluster`.

**Comment by cheshirbis** [comment]
Понял, большое спасибо!
