### ISSUE TITLE
It's impossible to choose bucket via yandex_cdn_origin_group

### ISSUE THREAD

**Issue by kvendingoldo** [yandex-cloud/terraform-provider-yandex#449]
Hi,
I noticed that when I'm trying to create yandex_cdn_origin_group, it's not possible to select bucket, as it possible in UI. Please, fix it because it blocks a lot of cases.

Also, I noticed that If I change type Host -> Bucket for yandex_cdn_origin_group in Yandex UI, terraform does not see these changes.

**Comment by max-arnold** [comment]
Duplicate of #373
