### ISSUE TITLE
GPG-ключ для registry.opentofu.org

### ISSUE THREAD

**Issue by efadeev** [yandex-cloud/terraform-provider-yandex#459]
При инициализации с использованием opentofu получаю предупреждение:
```
Initializing provider plugins...
- Finding latest version of yandex-cloud/yandex...
- Installing yandex-cloud/yandex v0.126.0...
- Installed yandex-cloud/yandex v0.126.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```
Дело в отсутствующем публичном GPG-ключе в opentofu registry:
https://github.com/opentofu/registry/tree/main/keys/y
Было бы прекрасно, если бы вы добавили туда ключ. Спасибо!

**Comment by dmchmk** [comment]
@efadeev привет! Фиксед, попробуй теперь?:)

**Comment by efadeev** [comment]
@dmchmk Да, теперь signed, спасибо большое!
