### ISSUE TITLE
CDN: ignore_query_params and proxy_cache_methods_set are changing by Yandex

### ISSUE THREAD

**Issue by sharovmerk** [yandex-cloud/terraform-provider-yandex#460]
В каждом запуске вижу такое, хотя через UI ничего не меняем
```
      ~ options {
          ~ ignore_query_params        = true -> false
          ~ proxy_cache_methods_set    = false -> true
            # (19 unchanged attributes hidden)
        }
```

**Comment by Fluffi1235** [comment]
@sharovmerk Привет! Можете предоставить свою конфигурацию tf

**Comment by nathanKith** [comment]
Не смогли получить нужную информацию для решения задачи. Если проблема возникнет вновь, создавайте, пожалуйста, новый issue.
