### ISSUE TITLE
Load Balancer support

### ISSUE THREAD

**Issue by kharkevich** [yandex-cloud/terraform-provider-yandex#6]
Hey,
I'll try to play with Yandex.Cloud but found no way to create Load Balancer.
Could you please help me with them.

**Comment by GennadySpb** [comment]
Hi! 

If you ask about help with usage Load Balancer service try [documentation](https://cloud.yandex.com/docs/load-balancer/) and [Support](https://cloud.yandex.com/support).

If the question of support resources and data source for  Load Balancer - their implementation in the nearest plans.

**Comment by kharkevich** [comment]
Hi @GennadySpb,
Thanks for your reply. Just one thing - could you please provide a little bit more details about "the nearest plans" :)
This is important for me, because I'm working on some demo, Yandex.Cloud used as selected provider for this demo and I would like to not a change provider on this demo.

**Comment by GennadySpb** [comment]
Hi @kharkevich !

Good news! New Load Balancer terraform resource (and data source) on the way. I guess a release will happen in a couple of weeks.

**Comment by GennadySpb** [comment]
Check version **0.9.0** - that contains new resource and data source for [Load Balancer](https://cloud.yandex.com/docs/load-balancer/concepts/) & [Target Group](https://cloud.yandex.com/docs/load-balancer/concepts/target-resources)
