### ISSUE TITLE
yandex_vpc_subnet does not detach route_table

### ISSUE THREAD

**Issue by denispastukhov** [yandex-cloud/terraform-provider-yandex#66]
After creating subnet with route table I'm unable to detach or delete route table.
Steps to reproduce:

- Create subnet with route table

```
resource "yandex_vpc_subnet" "lab-subnet-a" {
  v4_cidr_blocks = ["10.2.0.0/16"]
  zone           = "ru-central1-a"
  description    = "description"
  network_id     = yandex_vpc_network.this.id
  route_table_id = yandex_vpc_route_table.lab-rt-a.id
}

resource "yandex_vpc_route_table" "lab-rt-a" {
  network_id = yandex_vpc_network.this.id

  static_route {
    destination_prefix = "10.2.0.0/16"
    next_hop_address   = "172.16.10.10"
  }
}
```

- set  description and route_table_id to null, or comment whole lines. Terraform plan will be like:
```
resource "yandex_vpc_subnet" "lab-subnet-a" {
  v4_cidr_blocks = ["10.2.0.0/16"]
  zone           = "ru-central1-a"
  description    = null #"description"
  network_id     = yandex_vpc_network.this.id
  route_table_id = null #yandex_vpc_route_table.lab-rt-a.id
}
```
```
Terraform will perform the following actions:

  # yandex_vpc_subnet.lab-subnet-a will be updated in-place
  ~ resource "yandex_vpc_subnet" "lab-subnet-a" {
        created_at     = "2020-04-24T13:37:41Z"
      - description    = "description" -> null
        folder_id      = "b1gt0iskjdm3od1v1ugn"
        id             = "e9bmijvqccme1o24k6gb"
        labels         = {}
        network_id     = "enp6nelibq0barsg397n"
        route_table_id = "enp4hs4ss80qb481fqpp"
        v4_cidr_blocks = [
            "10.2.0.0/16",
        ]
        v6_cidr_blocks = []
        zone           = "ru-central1-a"
    }

```
Obviously, apply does not detach route table.
Also in interface i can see route table still attached after terraform apply.
![image](https://user-images.githubusercontent.com/43005042/80220749-fc7e6600-864c-11ea-9287-b47cd6707ad2.png)

- When i try to destroy yandex_vpc_route_table, i get error

> Error: error reading Route table "": server-request-id = 8f4d8d21-1b93-ba6e-b3b2-bd7d1982582c client-request-id = 9ceaa2ec-5e3d-4000-90b2-d8d96a39dff3 client-trace-id = 1528b1d2-bb9c-4761-aa19-fb334c0f051f rpc error: code = FailedPrecondition desc = Route table enp4hs4ss80qb481fqpp is associated with a subnet

However, it works as intended with description field. 

Provider version: 0.38
Terraform version: 0.12.24

**Comment by apilikov** [comment]
Thanks for reaching out. Do you still experience troubles with the issue with the latest provider?

**Comment by apilikov** [comment]
Closing the issue as there is no updates for a long time.
