### ISSUE TITLE
Yandex Cloud Function: Ability to create public functions

### ISSUE THREAD

**Issue by sergeyzwezdin** [yandex-cloud/terraform-provider-yandex#69]
For now, it's impossible to create Cloud Function with public access so this function available via HTTPS. It would be helpful to create public functions.

**Comment by GennadySpb** [comment]
@ChaoticCube1 please consider this request.

**Comment by monsterzz** [comment]
@sergeyzwezdin unfortunately there is no support for `yandex_function_iam_binding` at this moment. We've added this task to next iteration and keep you updated on progress.

**Comment by sergeyzwezdin** [comment]
@monsterzz thank you! Any ideas about ETA for this?

**Comment by monsterzz** [comment]
yep, already supported in latest version of provider: https://www.terraform.io/docs/providers/yandex/r/function_iam_binding.html
