### ISSUE TITLE
Yandex Object Storage: Custom SSL certificate for the storage

### ISSUE THREAD

**Issue by sergeyzwezdin** [yandex-cloud/terraform-provider-yandex#70]
It would be useful to be able to upload SSL certificates via Terraform provider for YOS while creating a bucket.

**Comment by izhidkov** [comment]
S3-compatible API specification does not include methods for uploading SSL certificates. We have some plans in roadmap for creating our own implementation which could be integrated with terraform provider, but at this point we can not guarantee any timing for it.

**Comment by apilikov** [comment]
Closing the issue as there is no updates for a long time.
