### ISSUE TITLE
What is ClickHouse Serverless access?

### ISSUE THREAD

**Issue by bryzgaloff** [yandex-cloud/terraform-provider-yandex#75]
What does `yandex_mdb_clickhouse_cluster.access.serverless` stand for? [The Terraform provider docs](https://www.terraform.io/docs/providers/yandex/r/mdb_clickhouse_cluster.html#serverless) say just «serverless - (Optional) Allow access for Serverless.» In the [service docs](https://cloud.yandex.com/docs/managed-clickhouse/operations/cluster-create) it is not mentioned at all. [Here it is](https://github.com/terraform-providers/terraform-provider-yandex/blob/1220938f160733b5c45d531d9b4b324e6a6de607/yandex/data_source_yandex_mdb_clickhouse_cluster.go#L181) in the resource definition.

Do I need to set the option to `true` if I need to access ClickHouse from my Cloud Function?

**Comment by GennadySpb** [comment]
@ChaoticCube1 please check this.

**Comment by bryzgaloff** [comment]
I have run some experiments on deploying ClickHouse cluster using Terraform and would like to share my results.

I have tried to create ClickHouse host either with `access.serverless=true` and `access.serverless=false` trying to access ClickHouse cluster from my Cloud Function. What have I got is:
* I could not connect to ClickHouse from Cloud Function at all if `assign_public_ip` is `false` or omitted (and thus `false` by default). Only by switching `assign_public_ip` to `true` I was able to connect to ClickHouse from Cloud Function.
* With `assign_public_ip=true` `access.serverless` seems to have no effect.

So maybe this is a more proper question: is there any way to connect to ClickHouse from Cloud Function without enabling public access to CH?

**Comment by monsterzz** [comment]
@bryzgaloff at this moment the only way to use ClickHouse is assigning public addresses to cluster. But we're working on more convenient way to work with ClickHouse and PostgreSQL databases, so `access.serverless` is just first step of this new project (no-op at this time).

**Comment by bryzgaloff** [comment]
@monsterzz could you please make a notice to this issue when it will be possible to connect from Cloud Function to ClickHouse without public access? For me not to miss it in the documentation. Thank you in advance.

It would be also nice to state in the documentation that `access.serverless` is no-op.

**Comment by monsterzz** [comment]
> @monsterzz could you please make a notice to this issue when it will be possible to connect from Cloud Function to ClickHouse without public access? For me not to miss it in the documentation. Thank you in advance.

Of course, there will be announcement about this new feature!
