### ISSUE TITLE
add DBMS settings in yandex_mdb_postgresql_cluster for users.

### ISSUE THREAD

**Issue by asterix201** [yandex-cloud/terraform-provider-yandex#78]
Hi, 

I think it could be very useful to add all or some DBMS settings for a user on database cluster and databases creation.
At least some of these settings, like connection limit, which could be a blocking point to create a new user/database.
As an example of an issue - we have a lot of small databases in one cluster and for each database, we use a dedicated user. 
By default connection limit for a user is 50 connections and if we use s2.small instance it is not possible to create more than 15 users with default parameters. 
Then we are facing a problem - how to add a new database and create a new user. 
And even we create a user with manual manipulating (decrease conn limits for all users to allow create a new with 50 connections, then update everything again). When we will need to recreate this cluster - it will be a problem.

Postgres provider is not very suitable here, as it connects to the database and check cluster and databases on plan step, before any actions. An if there is no user/database it will throw an error.

**Comment by apilikov** [comment]
Thanks for reaching out. Do you still experience troubles with the issue with the latest provider?

**Comment by asterix201** [comment]
no, with latest version we started to use settigns attribute and it solved this isuue. 
Thanks a lot!
