### ISSUE TITLE
Importing yandex_compute_instance resource doesn't set hostname parameter

### ISSUE THREAD

**Issue by Nyoroon** [yandex-cloud/terraform-provider-yandex#8]
Importing yandex_compute_instance resource doesn't set hostname parameter and forces recreation of resource. fqdn is imported correctly.

**Comment by GennadySpb** [comment]
Hello @Nyoroon !

According to public API spec call of [InstanceService/Get](https://github.com/yandex-cloud/cloudapi/blob/master/yandex/cloud/compute/v1/instance_service.proto#L19) method returns [Instance](https://github.com/yandex-cloud/cloudapi/blob/master/yandex/cloud/compute/v1/instance.proto#L10-L98) object that does not contain `Hostname` attribute.

There is [only place](https://github.com/yandex-cloud/cloudapi/blob/master/yandex/cloud/compute/v1/instance_service.proto#L229-L234) where this attribute used is `CreateInstanceRequest` message.

I think it would be wise to calculate `Hostname` parameter based on `Fqdn` value for Import operation.

**Comment by GennadySpb** [comment]
Hi @Nyoroon !
Check version [equal or above](https://github.com/terraform-providers/terraform-provider-yandex/blob/master/CHANGELOG.md#0350-march-31-2020) `0.35.0`: it contains fix to work correct with `hostname` field after import operation.

**Comment by Nyoroon** [comment]
I can't check that because I don't work with Yandex.Cloud anymore :cry:

**Comment by GennadySpb** [comment]
Oh.. (
Right now close issue.
