### ISSUE TITLE
Too small default timeout for creating snapshot

### ISSUE THREAD

**Issue by unixzen** [yandex-cloud/terraform-provider-yandex#87]
Hello!

I try make snapshot by terraform and after 20 minutes i get 
```
Error: Error while waiting operation to create snapshot: operation (id=epdasb79satrstnaoyrustwf) wait context done: context deadline exceeded
```
I suspect problem at this place https://github.com/terraform-providers/terraform-provider-yandex/blob/master/yandex/resource_yandex_compute_snapshot.go#L15

I create snapshot of disk size 100 Gb and snapshot is creating during 50 minutes.
Could you take out timeout parameter to configuration as describe here 
https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html#statechangeconf
Or hint me how i could be this realize. At yours SDK you working with timeout through context. I can't understand how could be stateConf binded with context at yours SDK.

Example how this at aws_db_instance configuration
https://www.terraform.io/docs/configuration/resources.html#operation-timeouts

**Comment by seukyaso** [comment]
You should be able to do exactly like in your 'aws' example. Try to add explicit create timeout to your resource:
  timeouts {
    create = "60m"
  }

**Comment by unixzen** [comment]
> You should be able to do exactly like in your 'aws' example. Try to add explicit create timeout to your resource:
> timeouts {
> create = "60m"
> }

Thanks a lot! All fine working! It would be fine if you add this information at documentation
https://www.terraform.io/docs/providers/yandex/r/compute_snapshot.html
