### ISSUE TITLE
any way to get service account id from "yandex_iam_service_account" resource?

### ISSUE THREAD

**Issue by yuanlinios** [yandex-cloud/terraform-provider-yandex#88]
According to https://www.terraform.io/docs/providers/yandex/r/iam_service_account.html, the resource "yandex_iam_service_account" accepts 3 arguments (name, description, folder_id), but does not provide any attribute. 

Then how can I reference this new service account in other resources?

**Comment by GennadySpb** [comment]
Hi @yuanlinios !

All terraform resources have `id` attribute. Just use reference to it.

**Comment by GennadySpb** [comment]
For example

```
resource "yandex_iam_service_account" "sa" {
  name        = "VM Manager"
  description = "service account to manage VMs"
}

resource "yandex_resourcemanager_folder_iam_member" "admin" {
  folder_id = "<some_folder_id>"

  role   = "editor"
  member = "serviceAccount:${yandex_iam_service_account.sa.id}"
}
```
```

**Comment by yuanlinios** [comment]
Hello @GennadySpb 

It works. Thank you for the info!
